package com.example.webredis.data;

import com.example.webredis.data.BdPsndocExample.Criteria;
import com.example.webredis.data.BdPsndocExample.Criterion;
import com.example.webredis.data.BdPsndocExample;
import com.example.webredis.data.BdPsndocWithBLOBs;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class BdPsndocSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BD_PSNDOC
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String countByExample(BdPsndocExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("BD_PSNDOC");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BD_PSNDOC
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String deleteByExample(BdPsndocExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("BD_PSNDOC");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BD_PSNDOC
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String insertSelective(BdPsndocWithBLOBs record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("BD_PSNDOC");
        
        if (record.getPkPsndoc() != null) {
            sql.VALUES("PK_PSNDOC", "#{pkPsndoc,jdbcType=CHAR}");
        }
        
        if (record.getAddr() != null) {
            sql.VALUES("ADDR", "#{addr,jdbcType=VARCHAR}");
        }
        
        if (record.getBirthdate() != null) {
            sql.VALUES("BIRTHDATE", "#{birthdate,jdbcType=CHAR}");
        }
        
        if (record.getCode() != null) {
            sql.VALUES("CODE", "#{code,jdbcType=VARCHAR}");
        }
        
        if (record.getCreationtime() != null) {
            sql.VALUES("CREATIONTIME", "#{creationtime,jdbcType=CHAR}");
        }
        
        if (record.getCreator() != null) {
            sql.VALUES("CREATOR", "#{creator,jdbcType=VARCHAR}");
        }
        
        if (record.getDataoriginflag() != null) {
            sql.VALUES("DATAORIGINFLAG", "#{dataoriginflag,jdbcType=DECIMAL}");
        }
        
        if (record.getDef1() != null) {
            sql.VALUES("DEF1", "#{def1,jdbcType=VARCHAR}");
        }
        
        if (record.getDef10() != null) {
            sql.VALUES("DEF10", "#{def10,jdbcType=VARCHAR}");
        }
        
        if (record.getDef11() != null) {
            sql.VALUES("DEF11", "#{def11,jdbcType=VARCHAR}");
        }
        
        if (record.getDef12() != null) {
            sql.VALUES("DEF12", "#{def12,jdbcType=VARCHAR}");
        }
        
        if (record.getDef13() != null) {
            sql.VALUES("DEF13", "#{def13,jdbcType=VARCHAR}");
        }
        
        if (record.getDef14() != null) {
            sql.VALUES("DEF14", "#{def14,jdbcType=VARCHAR}");
        }
        
        if (record.getDef15() != null) {
            sql.VALUES("DEF15", "#{def15,jdbcType=VARCHAR}");
        }
        
        if (record.getDef16() != null) {
            sql.VALUES("DEF16", "#{def16,jdbcType=VARCHAR}");
        }
        
        if (record.getDef17() != null) {
            sql.VALUES("DEF17", "#{def17,jdbcType=VARCHAR}");
        }
        
        if (record.getDef18() != null) {
            sql.VALUES("DEF18", "#{def18,jdbcType=VARCHAR}");
        }
        
        if (record.getDef19() != null) {
            sql.VALUES("DEF19", "#{def19,jdbcType=VARCHAR}");
        }
        
        if (record.getDef2() != null) {
            sql.VALUES("DEF2", "#{def2,jdbcType=VARCHAR}");
        }
        
        if (record.getDef20() != null) {
            sql.VALUES("DEF20", "#{def20,jdbcType=VARCHAR}");
        }
        
        if (record.getDef3() != null) {
            sql.VALUES("DEF3", "#{def3,jdbcType=VARCHAR}");
        }
        
        if (record.getDef4() != null) {
            sql.VALUES("DEF4", "#{def4,jdbcType=VARCHAR}");
        }
        
        if (record.getDef5() != null) {
            sql.VALUES("DEF5", "#{def5,jdbcType=VARCHAR}");
        }
        
        if (record.getDef6() != null) {
            sql.VALUES("DEF6", "#{def6,jdbcType=VARCHAR}");
        }
        
        if (record.getDef7() != null) {
            sql.VALUES("DEF7", "#{def7,jdbcType=VARCHAR}");
        }
        
        if (record.getDef8() != null) {
            sql.VALUES("DEF8", "#{def8,jdbcType=VARCHAR}");
        }
        
        if (record.getDef9() != null) {
            sql.VALUES("DEF9", "#{def9,jdbcType=VARCHAR}");
        }
        
        if (record.getDr() != null) {
            sql.VALUES("DR", "#{dr,jdbcType=DECIMAL}");
        }
        
        if (record.getEmail() != null) {
            sql.VALUES("EMAIL", "#{email,jdbcType=VARCHAR}");
        }
        
        if (record.getEnablestate() != null) {
            sql.VALUES("ENABLESTATE", "#{enablestate,jdbcType=DECIMAL}");
        }
        
        if (record.getFirstname() != null) {
            sql.VALUES("FIRSTNAME", "#{firstname,jdbcType=VARCHAR}");
        }
        
        if (record.getHomephone() != null) {
            sql.VALUES("HOMEPHONE", "#{homephone,jdbcType=VARCHAR}");
        }
        
        if (record.getId() != null) {
            sql.VALUES("ID", "#{id,jdbcType=VARCHAR}");
        }
        
        if (record.getIdtype() != null) {
            sql.VALUES("IDTYPE", "#{idtype,jdbcType=VARCHAR}");
        }
        
        if (record.getJoinworkdate() != null) {
            sql.VALUES("JOINWORKDATE", "#{joinworkdate,jdbcType=CHAR}");
        }
        
        if (record.getLastname() != null) {
            sql.VALUES("LASTNAME", "#{lastname,jdbcType=VARCHAR}");
        }
        
        if (record.getMnecode() != null) {
            sql.VALUES("MNECODE", "#{mnecode,jdbcType=VARCHAR}");
        }
        
        if (record.getMobile() != null) {
            sql.VALUES("MOBILE", "#{mobile,jdbcType=VARCHAR}");
        }
        
        if (record.getModifiedtime() != null) {
            sql.VALUES("MODIFIEDTIME", "#{modifiedtime,jdbcType=CHAR}");
        }
        
        if (record.getModifier() != null) {
            sql.VALUES("MODIFIER", "#{modifier,jdbcType=VARCHAR}");
        }
        
        if (record.getName() != null) {
            sql.VALUES("NAME", "#{name,jdbcType=VARCHAR}");
        }
        
        if (record.getName2() != null) {
            sql.VALUES("NAME2", "#{name2,jdbcType=VARCHAR}");
        }
        
        if (record.getName3() != null) {
            sql.VALUES("NAME3", "#{name3,jdbcType=VARCHAR}");
        }
        
        if (record.getName4() != null) {
            sql.VALUES("NAME4", "#{name4,jdbcType=VARCHAR}");
        }
        
        if (record.getName5() != null) {
            sql.VALUES("NAME5", "#{name5,jdbcType=VARCHAR}");
        }
        
        if (record.getName6() != null) {
            sql.VALUES("NAME6", "#{name6,jdbcType=VARCHAR}");
        }
        
        if (record.getNickname() != null) {
            sql.VALUES("NICKNAME", "#{nickname,jdbcType=VARCHAR}");
        }
        
        if (record.getOfficephone() != null) {
            sql.VALUES("OFFICEPHONE", "#{officephone,jdbcType=VARCHAR}");
        }
        
        if (record.getPkGroup() != null) {
            sql.VALUES("PK_GROUP", "#{pkGroup,jdbcType=VARCHAR}");
        }
        
        if (record.getPkOrg() != null) {
            sql.VALUES("PK_ORG", "#{pkOrg,jdbcType=VARCHAR}");
        }
        
        if (record.getSex() != null) {
            sql.VALUES("SEX", "#{sex,jdbcType=DECIMAL}");
        }
        
        if (record.getTs() != null) {
            sql.VALUES("TS", "#{ts,jdbcType=CHAR}");
        }
        
        if (record.getUsedname() != null) {
            sql.VALUES("USEDNAME", "#{usedname,jdbcType=VARCHAR}");
        }
        
        if (record.getIsshopassist() != null) {
            sql.VALUES("ISSHOPASSIST", "#{isshopassist,jdbcType=CHAR}");
        }
        
        if (record.getBloodtype() != null) {
            sql.VALUES("BLOODTYPE", "#{bloodtype,jdbcType=VARCHAR}");
        }
        
        if (record.getCensusaddr() != null) {
            sql.VALUES("CENSUSADDR", "#{censusaddr,jdbcType=VARCHAR}");
        }
        
        if (record.getCharacterrpr() != null) {
            sql.VALUES("CHARACTERRPR", "#{characterrpr,jdbcType=VARCHAR}");
        }
        
        if (record.getCountry() != null) {
            sql.VALUES("COUNTRY", "#{country,jdbcType=VARCHAR}");
        }
        
        if (record.getDieDate() != null) {
            sql.VALUES("DIE_DATE", "#{dieDate,jdbcType=CHAR}");
        }
        
        if (record.getDieRemark() != null) {
            sql.VALUES("DIE_REMARK", "#{dieRemark,jdbcType=VARCHAR}");
        }
        
        if (record.getEdu() != null) {
            sql.VALUES("EDU", "#{edu,jdbcType=VARCHAR}");
        }
        
        if (record.getFax() != null) {
            sql.VALUES("FAX", "#{fax,jdbcType=VARCHAR}");
        }
        
        if (record.getFileaddress() != null) {
            sql.VALUES("FILEADDRESS", "#{fileaddress,jdbcType=VARCHAR}");
        }
        
        if (record.getHealth() != null) {
            sql.VALUES("HEALTH", "#{health,jdbcType=VARCHAR}");
        }
        
        if (record.getIscadre() != null) {
            sql.VALUES("ISCADRE", "#{iscadre,jdbcType=CHAR}");
        }
        
        if (record.getIshiskeypsn() != null) {
            sql.VALUES("ISHISKEYPSN", "#{ishiskeypsn,jdbcType=CHAR}");
        }
        
        if (record.getIshisleader() != null) {
            sql.VALUES("ISHISLEADER", "#{ishisleader,jdbcType=CHAR}");
        }
        
        if (record.getJoinpolitydate() != null) {
            sql.VALUES("JOINPOLITYDATE", "#{joinpolitydate,jdbcType=CHAR}");
        }
        
        if (record.getMarital() != null) {
            sql.VALUES("MARITAL", "#{marital,jdbcType=VARCHAR}");
        }
        
        if (record.getMarriagedate() != null) {
            sql.VALUES("MARRIAGEDATE", "#{marriagedate,jdbcType=CHAR}");
        }
        
        if (record.getNationality() != null) {
            sql.VALUES("NATIONALITY", "#{nationality,jdbcType=VARCHAR}");
        }
        
        if (record.getNativeplace() != null) {
            sql.VALUES("NATIVEPLACE", "#{nativeplace,jdbcType=VARCHAR}");
        }
        
        if (record.getPenelauth() != null) {
            sql.VALUES("PENELAUTH", "#{penelauth,jdbcType=VARCHAR}");
        }
        
        if (record.getPermanreside() != null) {
            sql.VALUES("PERMANRESIDE", "#{permanreside,jdbcType=VARCHAR}");
        }
        
        if (record.getPkDegree() != null) {
            sql.VALUES("PK_DEGREE", "#{pkDegree,jdbcType=VARCHAR}");
        }
        
        if (record.getPkHrorg() != null) {
            sql.VALUES("PK_HRORG", "#{pkHrorg,jdbcType=VARCHAR}");
        }
        
        if (record.getPolity() != null) {
            sql.VALUES("POLITY", "#{polity,jdbcType=VARCHAR}");
        }
        
        if (record.getPostalcode() != null) {
            sql.VALUES("POSTALCODE", "#{postalcode,jdbcType=VARCHAR}");
        }
        
        if (record.getProf() != null) {
            sql.VALUES("PROF", "#{prof,jdbcType=CHAR}");
        }
        
        if (record.getRetiredate() != null) {
            sql.VALUES("RETIREDATE", "#{retiredate,jdbcType=CHAR}");
        }
        
        if (record.getSecretEmail() != null) {
            sql.VALUES("SECRET_EMAIL", "#{secretEmail,jdbcType=VARCHAR}");
        }
        
        if (record.getShortname() != null) {
            sql.VALUES("SHORTNAME", "#{shortname,jdbcType=VARCHAR}");
        }
        
        if (record.getTitletechpost() != null) {
            sql.VALUES("TITLETECHPOST", "#{titletechpost,jdbcType=VARCHAR}");
        }
        
        if (record.getAge() != null) {
            sql.VALUES("AGE", "#{age,jdbcType=VARCHAR}");
        }
        
        if (record.getWorkage() != null) {
            sql.VALUES("WORKAGE", "#{workage,jdbcType=VARCHAR}");
        }
        
        if (record.getPhoto() != null) {
            sql.VALUES("PHOTO", "#{photo,jdbcType=BLOB}");
        }
        
        if (record.getPreviewphoto() != null) {
            sql.VALUES("PREVIEWPHOTO", "#{previewphoto,jdbcType=BLOB}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BD_PSNDOC
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String selectByExampleWithBLOBs(BdPsndocExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("PK_PSNDOC");
        } else {
            sql.SELECT("PK_PSNDOC");
        }
        sql.SELECT("ADDR");
        sql.SELECT("BIRTHDATE");
        sql.SELECT("CODE");
        sql.SELECT("CREATIONTIME");
        sql.SELECT("CREATOR");
        sql.SELECT("DATAORIGINFLAG");
        sql.SELECT("DEF1");
        sql.SELECT("DEF10");
        sql.SELECT("DEF11");
        sql.SELECT("DEF12");
        sql.SELECT("DEF13");
        sql.SELECT("DEF14");
        sql.SELECT("DEF15");
        sql.SELECT("DEF16");
        sql.SELECT("DEF17");
        sql.SELECT("DEF18");
        sql.SELECT("DEF19");
        sql.SELECT("DEF2");
        sql.SELECT("DEF20");
        sql.SELECT("DEF3");
        sql.SELECT("DEF4");
        sql.SELECT("DEF5");
        sql.SELECT("DEF6");
        sql.SELECT("DEF7");
        sql.SELECT("DEF8");
        sql.SELECT("DEF9");
        sql.SELECT("DR");
        sql.SELECT("EMAIL");
        sql.SELECT("ENABLESTATE");
        sql.SELECT("FIRSTNAME");
        sql.SELECT("HOMEPHONE");
        sql.SELECT("ID");
        sql.SELECT("IDTYPE");
        sql.SELECT("JOINWORKDATE");
        sql.SELECT("LASTNAME");
        sql.SELECT("MNECODE");
        sql.SELECT("MOBILE");
        sql.SELECT("MODIFIEDTIME");
        sql.SELECT("MODIFIER");
        sql.SELECT("NAME");
        sql.SELECT("NAME2");
        sql.SELECT("NAME3");
        sql.SELECT("NAME4");
        sql.SELECT("NAME5");
        sql.SELECT("NAME6");
        sql.SELECT("NICKNAME");
        sql.SELECT("OFFICEPHONE");
        sql.SELECT("PK_GROUP");
        sql.SELECT("PK_ORG");
        sql.SELECT("SEX");
        sql.SELECT("TS");
        sql.SELECT("USEDNAME");
        sql.SELECT("ISSHOPASSIST");
        sql.SELECT("BLOODTYPE");
        sql.SELECT("CENSUSADDR");
        sql.SELECT("CHARACTERRPR");
        sql.SELECT("COUNTRY");
        sql.SELECT("DIE_DATE");
        sql.SELECT("DIE_REMARK");
        sql.SELECT("EDU");
        sql.SELECT("FAX");
        sql.SELECT("FILEADDRESS");
        sql.SELECT("HEALTH");
        sql.SELECT("ISCADRE");
        sql.SELECT("ISHISKEYPSN");
        sql.SELECT("ISHISLEADER");
        sql.SELECT("JOINPOLITYDATE");
        sql.SELECT("MARITAL");
        sql.SELECT("MARRIAGEDATE");
        sql.SELECT("NATIONALITY");
        sql.SELECT("NATIVEPLACE");
        sql.SELECT("PENELAUTH");
        sql.SELECT("PERMANRESIDE");
        sql.SELECT("PK_DEGREE");
        sql.SELECT("PK_HRORG");
        sql.SELECT("POLITY");
        sql.SELECT("POSTALCODE");
        sql.SELECT("PROF");
        sql.SELECT("RETIREDATE");
        sql.SELECT("SECRET_EMAIL");
        sql.SELECT("SHORTNAME");
        sql.SELECT("TITLETECHPOST");
        sql.SELECT("AGE");
        sql.SELECT("WORKAGE");
        sql.SELECT("PHOTO");
        sql.SELECT("PREVIEWPHOTO");
        sql.FROM("BD_PSNDOC");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BD_PSNDOC
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String selectByExample(BdPsndocExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("PK_PSNDOC");
        } else {
            sql.SELECT("PK_PSNDOC");
        }
        sql.SELECT("ADDR");
        sql.SELECT("BIRTHDATE");
        sql.SELECT("CODE");
        sql.SELECT("CREATIONTIME");
        sql.SELECT("CREATOR");
        sql.SELECT("DATAORIGINFLAG");
        sql.SELECT("DEF1");
        sql.SELECT("DEF10");
        sql.SELECT("DEF11");
        sql.SELECT("DEF12");
        sql.SELECT("DEF13");
        sql.SELECT("DEF14");
        sql.SELECT("DEF15");
        sql.SELECT("DEF16");
        sql.SELECT("DEF17");
        sql.SELECT("DEF18");
        sql.SELECT("DEF19");
        sql.SELECT("DEF2");
        sql.SELECT("DEF20");
        sql.SELECT("DEF3");
        sql.SELECT("DEF4");
        sql.SELECT("DEF5");
        sql.SELECT("DEF6");
        sql.SELECT("DEF7");
        sql.SELECT("DEF8");
        sql.SELECT("DEF9");
        sql.SELECT("DR");
        sql.SELECT("EMAIL");
        sql.SELECT("ENABLESTATE");
        sql.SELECT("FIRSTNAME");
        sql.SELECT("HOMEPHONE");
        sql.SELECT("ID");
        sql.SELECT("IDTYPE");
        sql.SELECT("JOINWORKDATE");
        sql.SELECT("LASTNAME");
        sql.SELECT("MNECODE");
        sql.SELECT("MOBILE");
        sql.SELECT("MODIFIEDTIME");
        sql.SELECT("MODIFIER");
        sql.SELECT("NAME");
        sql.SELECT("NAME2");
        sql.SELECT("NAME3");
        sql.SELECT("NAME4");
        sql.SELECT("NAME5");
        sql.SELECT("NAME6");
        sql.SELECT("NICKNAME");
        sql.SELECT("OFFICEPHONE");
        sql.SELECT("PK_GROUP");
        sql.SELECT("PK_ORG");
        sql.SELECT("SEX");
        sql.SELECT("TS");
        sql.SELECT("USEDNAME");
        sql.SELECT("ISSHOPASSIST");
        sql.SELECT("BLOODTYPE");
        sql.SELECT("CENSUSADDR");
        sql.SELECT("CHARACTERRPR");
        sql.SELECT("COUNTRY");
        sql.SELECT("DIE_DATE");
        sql.SELECT("DIE_REMARK");
        sql.SELECT("EDU");
        sql.SELECT("FAX");
        sql.SELECT("FILEADDRESS");
        sql.SELECT("HEALTH");
        sql.SELECT("ISCADRE");
        sql.SELECT("ISHISKEYPSN");
        sql.SELECT("ISHISLEADER");
        sql.SELECT("JOINPOLITYDATE");
        sql.SELECT("MARITAL");
        sql.SELECT("MARRIAGEDATE");
        sql.SELECT("NATIONALITY");
        sql.SELECT("NATIVEPLACE");
        sql.SELECT("PENELAUTH");
        sql.SELECT("PERMANRESIDE");
        sql.SELECT("PK_DEGREE");
        sql.SELECT("PK_HRORG");
        sql.SELECT("POLITY");
        sql.SELECT("POSTALCODE");
        sql.SELECT("PROF");
        sql.SELECT("RETIREDATE");
        sql.SELECT("SECRET_EMAIL");
        sql.SELECT("SHORTNAME");
        sql.SELECT("TITLETECHPOST");
        sql.SELECT("AGE");
        sql.SELECT("WORKAGE");
        sql.FROM("BD_PSNDOC");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BD_PSNDOC
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        BdPsndocWithBLOBs record = (BdPsndocWithBLOBs) parameter.get("record");
        BdPsndocExample example = (BdPsndocExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("BD_PSNDOC");
        
        if (record.getPkPsndoc() != null) {
            sql.SET("PK_PSNDOC = #{record.pkPsndoc,jdbcType=CHAR}");
        }
        
        if (record.getAddr() != null) {
            sql.SET("ADDR = #{record.addr,jdbcType=VARCHAR}");
        }
        
        if (record.getBirthdate() != null) {
            sql.SET("BIRTHDATE = #{record.birthdate,jdbcType=CHAR}");
        }
        
        if (record.getCode() != null) {
            sql.SET("CODE = #{record.code,jdbcType=VARCHAR}");
        }
        
        if (record.getCreationtime() != null) {
            sql.SET("CREATIONTIME = #{record.creationtime,jdbcType=CHAR}");
        }
        
        if (record.getCreator() != null) {
            sql.SET("CREATOR = #{record.creator,jdbcType=VARCHAR}");
        }
        
        if (record.getDataoriginflag() != null) {
            sql.SET("DATAORIGINFLAG = #{record.dataoriginflag,jdbcType=DECIMAL}");
        }
        
        if (record.getDef1() != null) {
            sql.SET("DEF1 = #{record.def1,jdbcType=VARCHAR}");
        }
        
        if (record.getDef10() != null) {
            sql.SET("DEF10 = #{record.def10,jdbcType=VARCHAR}");
        }
        
        if (record.getDef11() != null) {
            sql.SET("DEF11 = #{record.def11,jdbcType=VARCHAR}");
        }
        
        if (record.getDef12() != null) {
            sql.SET("DEF12 = #{record.def12,jdbcType=VARCHAR}");
        }
        
        if (record.getDef13() != null) {
            sql.SET("DEF13 = #{record.def13,jdbcType=VARCHAR}");
        }
        
        if (record.getDef14() != null) {
            sql.SET("DEF14 = #{record.def14,jdbcType=VARCHAR}");
        }
        
        if (record.getDef15() != null) {
            sql.SET("DEF15 = #{record.def15,jdbcType=VARCHAR}");
        }
        
        if (record.getDef16() != null) {
            sql.SET("DEF16 = #{record.def16,jdbcType=VARCHAR}");
        }
        
        if (record.getDef17() != null) {
            sql.SET("DEF17 = #{record.def17,jdbcType=VARCHAR}");
        }
        
        if (record.getDef18() != null) {
            sql.SET("DEF18 = #{record.def18,jdbcType=VARCHAR}");
        }
        
        if (record.getDef19() != null) {
            sql.SET("DEF19 = #{record.def19,jdbcType=VARCHAR}");
        }
        
        if (record.getDef2() != null) {
            sql.SET("DEF2 = #{record.def2,jdbcType=VARCHAR}");
        }
        
        if (record.getDef20() != null) {
            sql.SET("DEF20 = #{record.def20,jdbcType=VARCHAR}");
        }
        
        if (record.getDef3() != null) {
            sql.SET("DEF3 = #{record.def3,jdbcType=VARCHAR}");
        }
        
        if (record.getDef4() != null) {
            sql.SET("DEF4 = #{record.def4,jdbcType=VARCHAR}");
        }
        
        if (record.getDef5() != null) {
            sql.SET("DEF5 = #{record.def5,jdbcType=VARCHAR}");
        }
        
        if (record.getDef6() != null) {
            sql.SET("DEF6 = #{record.def6,jdbcType=VARCHAR}");
        }
        
        if (record.getDef7() != null) {
            sql.SET("DEF7 = #{record.def7,jdbcType=VARCHAR}");
        }
        
        if (record.getDef8() != null) {
            sql.SET("DEF8 = #{record.def8,jdbcType=VARCHAR}");
        }
        
        if (record.getDef9() != null) {
            sql.SET("DEF9 = #{record.def9,jdbcType=VARCHAR}");
        }
        
        if (record.getDr() != null) {
            sql.SET("DR = #{record.dr,jdbcType=DECIMAL}");
        }
        
        if (record.getEmail() != null) {
            sql.SET("EMAIL = #{record.email,jdbcType=VARCHAR}");
        }
        
        if (record.getEnablestate() != null) {
            sql.SET("ENABLESTATE = #{record.enablestate,jdbcType=DECIMAL}");
        }
        
        if (record.getFirstname() != null) {
            sql.SET("FIRSTNAME = #{record.firstname,jdbcType=VARCHAR}");
        }
        
        if (record.getHomephone() != null) {
            sql.SET("HOMEPHONE = #{record.homephone,jdbcType=VARCHAR}");
        }
        
        if (record.getId() != null) {
            sql.SET("ID = #{record.id,jdbcType=VARCHAR}");
        }
        
        if (record.getIdtype() != null) {
            sql.SET("IDTYPE = #{record.idtype,jdbcType=VARCHAR}");
        }
        
        if (record.getJoinworkdate() != null) {
            sql.SET("JOINWORKDATE = #{record.joinworkdate,jdbcType=CHAR}");
        }
        
        if (record.getLastname() != null) {
            sql.SET("LASTNAME = #{record.lastname,jdbcType=VARCHAR}");
        }
        
        if (record.getMnecode() != null) {
            sql.SET("MNECODE = #{record.mnecode,jdbcType=VARCHAR}");
        }
        
        if (record.getMobile() != null) {
            sql.SET("MOBILE = #{record.mobile,jdbcType=VARCHAR}");
        }
        
        if (record.getModifiedtime() != null) {
            sql.SET("MODIFIEDTIME = #{record.modifiedtime,jdbcType=CHAR}");
        }
        
        if (record.getModifier() != null) {
            sql.SET("MODIFIER = #{record.modifier,jdbcType=VARCHAR}");
        }
        
        if (record.getName() != null) {
            sql.SET("NAME = #{record.name,jdbcType=VARCHAR}");
        }
        
        if (record.getName2() != null) {
            sql.SET("NAME2 = #{record.name2,jdbcType=VARCHAR}");
        }
        
        if (record.getName3() != null) {
            sql.SET("NAME3 = #{record.name3,jdbcType=VARCHAR}");
        }
        
        if (record.getName4() != null) {
            sql.SET("NAME4 = #{record.name4,jdbcType=VARCHAR}");
        }
        
        if (record.getName5() != null) {
            sql.SET("NAME5 = #{record.name5,jdbcType=VARCHAR}");
        }
        
        if (record.getName6() != null) {
            sql.SET("NAME6 = #{record.name6,jdbcType=VARCHAR}");
        }
        
        if (record.getNickname() != null) {
            sql.SET("NICKNAME = #{record.nickname,jdbcType=VARCHAR}");
        }
        
        if (record.getOfficephone() != null) {
            sql.SET("OFFICEPHONE = #{record.officephone,jdbcType=VARCHAR}");
        }
        
        if (record.getPkGroup() != null) {
            sql.SET("PK_GROUP = #{record.pkGroup,jdbcType=VARCHAR}");
        }
        
        if (record.getPkOrg() != null) {
            sql.SET("PK_ORG = #{record.pkOrg,jdbcType=VARCHAR}");
        }
        
        if (record.getSex() != null) {
            sql.SET("SEX = #{record.sex,jdbcType=DECIMAL}");
        }
        
        if (record.getTs() != null) {
            sql.SET("TS = #{record.ts,jdbcType=CHAR}");
        }
        
        if (record.getUsedname() != null) {
            sql.SET("USEDNAME = #{record.usedname,jdbcType=VARCHAR}");
        }
        
        if (record.getIsshopassist() != null) {
            sql.SET("ISSHOPASSIST = #{record.isshopassist,jdbcType=CHAR}");
        }
        
        if (record.getBloodtype() != null) {
            sql.SET("BLOODTYPE = #{record.bloodtype,jdbcType=VARCHAR}");
        }
        
        if (record.getCensusaddr() != null) {
            sql.SET("CENSUSADDR = #{record.censusaddr,jdbcType=VARCHAR}");
        }
        
        if (record.getCharacterrpr() != null) {
            sql.SET("CHARACTERRPR = #{record.characterrpr,jdbcType=VARCHAR}");
        }
        
        if (record.getCountry() != null) {
            sql.SET("COUNTRY = #{record.country,jdbcType=VARCHAR}");
        }
        
        if (record.getDieDate() != null) {
            sql.SET("DIE_DATE = #{record.dieDate,jdbcType=CHAR}");
        }
        
        if (record.getDieRemark() != null) {
            sql.SET("DIE_REMARK = #{record.dieRemark,jdbcType=VARCHAR}");
        }
        
        if (record.getEdu() != null) {
            sql.SET("EDU = #{record.edu,jdbcType=VARCHAR}");
        }
        
        if (record.getFax() != null) {
            sql.SET("FAX = #{record.fax,jdbcType=VARCHAR}");
        }
        
        if (record.getFileaddress() != null) {
            sql.SET("FILEADDRESS = #{record.fileaddress,jdbcType=VARCHAR}");
        }
        
        if (record.getHealth() != null) {
            sql.SET("HEALTH = #{record.health,jdbcType=VARCHAR}");
        }
        
        if (record.getIscadre() != null) {
            sql.SET("ISCADRE = #{record.iscadre,jdbcType=CHAR}");
        }
        
        if (record.getIshiskeypsn() != null) {
            sql.SET("ISHISKEYPSN = #{record.ishiskeypsn,jdbcType=CHAR}");
        }
        
        if (record.getIshisleader() != null) {
            sql.SET("ISHISLEADER = #{record.ishisleader,jdbcType=CHAR}");
        }
        
        if (record.getJoinpolitydate() != null) {
            sql.SET("JOINPOLITYDATE = #{record.joinpolitydate,jdbcType=CHAR}");
        }
        
        if (record.getMarital() != null) {
            sql.SET("MARITAL = #{record.marital,jdbcType=VARCHAR}");
        }
        
        if (record.getMarriagedate() != null) {
            sql.SET("MARRIAGEDATE = #{record.marriagedate,jdbcType=CHAR}");
        }
        
        if (record.getNationality() != null) {
            sql.SET("NATIONALITY = #{record.nationality,jdbcType=VARCHAR}");
        }
        
        if (record.getNativeplace() != null) {
            sql.SET("NATIVEPLACE = #{record.nativeplace,jdbcType=VARCHAR}");
        }
        
        if (record.getPenelauth() != null) {
            sql.SET("PENELAUTH = #{record.penelauth,jdbcType=VARCHAR}");
        }
        
        if (record.getPermanreside() != null) {
            sql.SET("PERMANRESIDE = #{record.permanreside,jdbcType=VARCHAR}");
        }
        
        if (record.getPkDegree() != null) {
            sql.SET("PK_DEGREE = #{record.pkDegree,jdbcType=VARCHAR}");
        }
        
        if (record.getPkHrorg() != null) {
            sql.SET("PK_HRORG = #{record.pkHrorg,jdbcType=VARCHAR}");
        }
        
        if (record.getPolity() != null) {
            sql.SET("POLITY = #{record.polity,jdbcType=VARCHAR}");
        }
        
        if (record.getPostalcode() != null) {
            sql.SET("POSTALCODE = #{record.postalcode,jdbcType=VARCHAR}");
        }
        
        if (record.getProf() != null) {
            sql.SET("PROF = #{record.prof,jdbcType=CHAR}");
        }
        
        if (record.getRetiredate() != null) {
            sql.SET("RETIREDATE = #{record.retiredate,jdbcType=CHAR}");
        }
        
        if (record.getSecretEmail() != null) {
            sql.SET("SECRET_EMAIL = #{record.secretEmail,jdbcType=VARCHAR}");
        }
        
        if (record.getShortname() != null) {
            sql.SET("SHORTNAME = #{record.shortname,jdbcType=VARCHAR}");
        }
        
        if (record.getTitletechpost() != null) {
            sql.SET("TITLETECHPOST = #{record.titletechpost,jdbcType=VARCHAR}");
        }
        
        if (record.getAge() != null) {
            sql.SET("AGE = #{record.age,jdbcType=VARCHAR}");
        }
        
        if (record.getWorkage() != null) {
            sql.SET("WORKAGE = #{record.workage,jdbcType=VARCHAR}");
        }
        
        if (record.getPhoto() != null) {
            sql.SET("PHOTO = #{record.photo,jdbcType=BLOB}");
        }
        
        if (record.getPreviewphoto() != null) {
            sql.SET("PREVIEWPHOTO = #{record.previewphoto,jdbcType=BLOB}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BD_PSNDOC
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String updateByExampleWithBLOBs(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("BD_PSNDOC");
        
        sql.SET("PK_PSNDOC = #{record.pkPsndoc,jdbcType=CHAR}");
        sql.SET("ADDR = #{record.addr,jdbcType=VARCHAR}");
        sql.SET("BIRTHDATE = #{record.birthdate,jdbcType=CHAR}");
        sql.SET("CODE = #{record.code,jdbcType=VARCHAR}");
        sql.SET("CREATIONTIME = #{record.creationtime,jdbcType=CHAR}");
        sql.SET("CREATOR = #{record.creator,jdbcType=VARCHAR}");
        sql.SET("DATAORIGINFLAG = #{record.dataoriginflag,jdbcType=DECIMAL}");
        sql.SET("DEF1 = #{record.def1,jdbcType=VARCHAR}");
        sql.SET("DEF10 = #{record.def10,jdbcType=VARCHAR}");
        sql.SET("DEF11 = #{record.def11,jdbcType=VARCHAR}");
        sql.SET("DEF12 = #{record.def12,jdbcType=VARCHAR}");
        sql.SET("DEF13 = #{record.def13,jdbcType=VARCHAR}");
        sql.SET("DEF14 = #{record.def14,jdbcType=VARCHAR}");
        sql.SET("DEF15 = #{record.def15,jdbcType=VARCHAR}");
        sql.SET("DEF16 = #{record.def16,jdbcType=VARCHAR}");
        sql.SET("DEF17 = #{record.def17,jdbcType=VARCHAR}");
        sql.SET("DEF18 = #{record.def18,jdbcType=VARCHAR}");
        sql.SET("DEF19 = #{record.def19,jdbcType=VARCHAR}");
        sql.SET("DEF2 = #{record.def2,jdbcType=VARCHAR}");
        sql.SET("DEF20 = #{record.def20,jdbcType=VARCHAR}");
        sql.SET("DEF3 = #{record.def3,jdbcType=VARCHAR}");
        sql.SET("DEF4 = #{record.def4,jdbcType=VARCHAR}");
        sql.SET("DEF5 = #{record.def5,jdbcType=VARCHAR}");
        sql.SET("DEF6 = #{record.def6,jdbcType=VARCHAR}");
        sql.SET("DEF7 = #{record.def7,jdbcType=VARCHAR}");
        sql.SET("DEF8 = #{record.def8,jdbcType=VARCHAR}");
        sql.SET("DEF9 = #{record.def9,jdbcType=VARCHAR}");
        sql.SET("DR = #{record.dr,jdbcType=DECIMAL}");
        sql.SET("EMAIL = #{record.email,jdbcType=VARCHAR}");
        sql.SET("ENABLESTATE = #{record.enablestate,jdbcType=DECIMAL}");
        sql.SET("FIRSTNAME = #{record.firstname,jdbcType=VARCHAR}");
        sql.SET("HOMEPHONE = #{record.homephone,jdbcType=VARCHAR}");
        sql.SET("ID = #{record.id,jdbcType=VARCHAR}");
        sql.SET("IDTYPE = #{record.idtype,jdbcType=VARCHAR}");
        sql.SET("JOINWORKDATE = #{record.joinworkdate,jdbcType=CHAR}");
        sql.SET("LASTNAME = #{record.lastname,jdbcType=VARCHAR}");
        sql.SET("MNECODE = #{record.mnecode,jdbcType=VARCHAR}");
        sql.SET("MOBILE = #{record.mobile,jdbcType=VARCHAR}");
        sql.SET("MODIFIEDTIME = #{record.modifiedtime,jdbcType=CHAR}");
        sql.SET("MODIFIER = #{record.modifier,jdbcType=VARCHAR}");
        sql.SET("NAME = #{record.name,jdbcType=VARCHAR}");
        sql.SET("NAME2 = #{record.name2,jdbcType=VARCHAR}");
        sql.SET("NAME3 = #{record.name3,jdbcType=VARCHAR}");
        sql.SET("NAME4 = #{record.name4,jdbcType=VARCHAR}");
        sql.SET("NAME5 = #{record.name5,jdbcType=VARCHAR}");
        sql.SET("NAME6 = #{record.name6,jdbcType=VARCHAR}");
        sql.SET("NICKNAME = #{record.nickname,jdbcType=VARCHAR}");
        sql.SET("OFFICEPHONE = #{record.officephone,jdbcType=VARCHAR}");
        sql.SET("PK_GROUP = #{record.pkGroup,jdbcType=VARCHAR}");
        sql.SET("PK_ORG = #{record.pkOrg,jdbcType=VARCHAR}");
        sql.SET("SEX = #{record.sex,jdbcType=DECIMAL}");
        sql.SET("TS = #{record.ts,jdbcType=CHAR}");
        sql.SET("USEDNAME = #{record.usedname,jdbcType=VARCHAR}");
        sql.SET("ISSHOPASSIST = #{record.isshopassist,jdbcType=CHAR}");
        sql.SET("BLOODTYPE = #{record.bloodtype,jdbcType=VARCHAR}");
        sql.SET("CENSUSADDR = #{record.censusaddr,jdbcType=VARCHAR}");
        sql.SET("CHARACTERRPR = #{record.characterrpr,jdbcType=VARCHAR}");
        sql.SET("COUNTRY = #{record.country,jdbcType=VARCHAR}");
        sql.SET("DIE_DATE = #{record.dieDate,jdbcType=CHAR}");
        sql.SET("DIE_REMARK = #{record.dieRemark,jdbcType=VARCHAR}");
        sql.SET("EDU = #{record.edu,jdbcType=VARCHAR}");
        sql.SET("FAX = #{record.fax,jdbcType=VARCHAR}");
        sql.SET("FILEADDRESS = #{record.fileaddress,jdbcType=VARCHAR}");
        sql.SET("HEALTH = #{record.health,jdbcType=VARCHAR}");
        sql.SET("ISCADRE = #{record.iscadre,jdbcType=CHAR}");
        sql.SET("ISHISKEYPSN = #{record.ishiskeypsn,jdbcType=CHAR}");
        sql.SET("ISHISLEADER = #{record.ishisleader,jdbcType=CHAR}");
        sql.SET("JOINPOLITYDATE = #{record.joinpolitydate,jdbcType=CHAR}");
        sql.SET("MARITAL = #{record.marital,jdbcType=VARCHAR}");
        sql.SET("MARRIAGEDATE = #{record.marriagedate,jdbcType=CHAR}");
        sql.SET("NATIONALITY = #{record.nationality,jdbcType=VARCHAR}");
        sql.SET("NATIVEPLACE = #{record.nativeplace,jdbcType=VARCHAR}");
        sql.SET("PENELAUTH = #{record.penelauth,jdbcType=VARCHAR}");
        sql.SET("PERMANRESIDE = #{record.permanreside,jdbcType=VARCHAR}");
        sql.SET("PK_DEGREE = #{record.pkDegree,jdbcType=VARCHAR}");
        sql.SET("PK_HRORG = #{record.pkHrorg,jdbcType=VARCHAR}");
        sql.SET("POLITY = #{record.polity,jdbcType=VARCHAR}");
        sql.SET("POSTALCODE = #{record.postalcode,jdbcType=VARCHAR}");
        sql.SET("PROF = #{record.prof,jdbcType=CHAR}");
        sql.SET("RETIREDATE = #{record.retiredate,jdbcType=CHAR}");
        sql.SET("SECRET_EMAIL = #{record.secretEmail,jdbcType=VARCHAR}");
        sql.SET("SHORTNAME = #{record.shortname,jdbcType=VARCHAR}");
        sql.SET("TITLETECHPOST = #{record.titletechpost,jdbcType=VARCHAR}");
        sql.SET("AGE = #{record.age,jdbcType=VARCHAR}");
        sql.SET("WORKAGE = #{record.workage,jdbcType=VARCHAR}");
        sql.SET("PHOTO = #{record.photo,jdbcType=BLOB}");
        sql.SET("PREVIEWPHOTO = #{record.previewphoto,jdbcType=BLOB}");
        
        BdPsndocExample example = (BdPsndocExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BD_PSNDOC
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("BD_PSNDOC");
        
        sql.SET("PK_PSNDOC = #{record.pkPsndoc,jdbcType=CHAR}");
        sql.SET("ADDR = #{record.addr,jdbcType=VARCHAR}");
        sql.SET("BIRTHDATE = #{record.birthdate,jdbcType=CHAR}");
        sql.SET("CODE = #{record.code,jdbcType=VARCHAR}");
        sql.SET("CREATIONTIME = #{record.creationtime,jdbcType=CHAR}");
        sql.SET("CREATOR = #{record.creator,jdbcType=VARCHAR}");
        sql.SET("DATAORIGINFLAG = #{record.dataoriginflag,jdbcType=DECIMAL}");
        sql.SET("DEF1 = #{record.def1,jdbcType=VARCHAR}");
        sql.SET("DEF10 = #{record.def10,jdbcType=VARCHAR}");
        sql.SET("DEF11 = #{record.def11,jdbcType=VARCHAR}");
        sql.SET("DEF12 = #{record.def12,jdbcType=VARCHAR}");
        sql.SET("DEF13 = #{record.def13,jdbcType=VARCHAR}");
        sql.SET("DEF14 = #{record.def14,jdbcType=VARCHAR}");
        sql.SET("DEF15 = #{record.def15,jdbcType=VARCHAR}");
        sql.SET("DEF16 = #{record.def16,jdbcType=VARCHAR}");
        sql.SET("DEF17 = #{record.def17,jdbcType=VARCHAR}");
        sql.SET("DEF18 = #{record.def18,jdbcType=VARCHAR}");
        sql.SET("DEF19 = #{record.def19,jdbcType=VARCHAR}");
        sql.SET("DEF2 = #{record.def2,jdbcType=VARCHAR}");
        sql.SET("DEF20 = #{record.def20,jdbcType=VARCHAR}");
        sql.SET("DEF3 = #{record.def3,jdbcType=VARCHAR}");
        sql.SET("DEF4 = #{record.def4,jdbcType=VARCHAR}");
        sql.SET("DEF5 = #{record.def5,jdbcType=VARCHAR}");
        sql.SET("DEF6 = #{record.def6,jdbcType=VARCHAR}");
        sql.SET("DEF7 = #{record.def7,jdbcType=VARCHAR}");
        sql.SET("DEF8 = #{record.def8,jdbcType=VARCHAR}");
        sql.SET("DEF9 = #{record.def9,jdbcType=VARCHAR}");
        sql.SET("DR = #{record.dr,jdbcType=DECIMAL}");
        sql.SET("EMAIL = #{record.email,jdbcType=VARCHAR}");
        sql.SET("ENABLESTATE = #{record.enablestate,jdbcType=DECIMAL}");
        sql.SET("FIRSTNAME = #{record.firstname,jdbcType=VARCHAR}");
        sql.SET("HOMEPHONE = #{record.homephone,jdbcType=VARCHAR}");
        sql.SET("ID = #{record.id,jdbcType=VARCHAR}");
        sql.SET("IDTYPE = #{record.idtype,jdbcType=VARCHAR}");
        sql.SET("JOINWORKDATE = #{record.joinworkdate,jdbcType=CHAR}");
        sql.SET("LASTNAME = #{record.lastname,jdbcType=VARCHAR}");
        sql.SET("MNECODE = #{record.mnecode,jdbcType=VARCHAR}");
        sql.SET("MOBILE = #{record.mobile,jdbcType=VARCHAR}");
        sql.SET("MODIFIEDTIME = #{record.modifiedtime,jdbcType=CHAR}");
        sql.SET("MODIFIER = #{record.modifier,jdbcType=VARCHAR}");
        sql.SET("NAME = #{record.name,jdbcType=VARCHAR}");
        sql.SET("NAME2 = #{record.name2,jdbcType=VARCHAR}");
        sql.SET("NAME3 = #{record.name3,jdbcType=VARCHAR}");
        sql.SET("NAME4 = #{record.name4,jdbcType=VARCHAR}");
        sql.SET("NAME5 = #{record.name5,jdbcType=VARCHAR}");
        sql.SET("NAME6 = #{record.name6,jdbcType=VARCHAR}");
        sql.SET("NICKNAME = #{record.nickname,jdbcType=VARCHAR}");
        sql.SET("OFFICEPHONE = #{record.officephone,jdbcType=VARCHAR}");
        sql.SET("PK_GROUP = #{record.pkGroup,jdbcType=VARCHAR}");
        sql.SET("PK_ORG = #{record.pkOrg,jdbcType=VARCHAR}");
        sql.SET("SEX = #{record.sex,jdbcType=DECIMAL}");
        sql.SET("TS = #{record.ts,jdbcType=CHAR}");
        sql.SET("USEDNAME = #{record.usedname,jdbcType=VARCHAR}");
        sql.SET("ISSHOPASSIST = #{record.isshopassist,jdbcType=CHAR}");
        sql.SET("BLOODTYPE = #{record.bloodtype,jdbcType=VARCHAR}");
        sql.SET("CENSUSADDR = #{record.censusaddr,jdbcType=VARCHAR}");
        sql.SET("CHARACTERRPR = #{record.characterrpr,jdbcType=VARCHAR}");
        sql.SET("COUNTRY = #{record.country,jdbcType=VARCHAR}");
        sql.SET("DIE_DATE = #{record.dieDate,jdbcType=CHAR}");
        sql.SET("DIE_REMARK = #{record.dieRemark,jdbcType=VARCHAR}");
        sql.SET("EDU = #{record.edu,jdbcType=VARCHAR}");
        sql.SET("FAX = #{record.fax,jdbcType=VARCHAR}");
        sql.SET("FILEADDRESS = #{record.fileaddress,jdbcType=VARCHAR}");
        sql.SET("HEALTH = #{record.health,jdbcType=VARCHAR}");
        sql.SET("ISCADRE = #{record.iscadre,jdbcType=CHAR}");
        sql.SET("ISHISKEYPSN = #{record.ishiskeypsn,jdbcType=CHAR}");
        sql.SET("ISHISLEADER = #{record.ishisleader,jdbcType=CHAR}");
        sql.SET("JOINPOLITYDATE = #{record.joinpolitydate,jdbcType=CHAR}");
        sql.SET("MARITAL = #{record.marital,jdbcType=VARCHAR}");
        sql.SET("MARRIAGEDATE = #{record.marriagedate,jdbcType=CHAR}");
        sql.SET("NATIONALITY = #{record.nationality,jdbcType=VARCHAR}");
        sql.SET("NATIVEPLACE = #{record.nativeplace,jdbcType=VARCHAR}");
        sql.SET("PENELAUTH = #{record.penelauth,jdbcType=VARCHAR}");
        sql.SET("PERMANRESIDE = #{record.permanreside,jdbcType=VARCHAR}");
        sql.SET("PK_DEGREE = #{record.pkDegree,jdbcType=VARCHAR}");
        sql.SET("PK_HRORG = #{record.pkHrorg,jdbcType=VARCHAR}");
        sql.SET("POLITY = #{record.polity,jdbcType=VARCHAR}");
        sql.SET("POSTALCODE = #{record.postalcode,jdbcType=VARCHAR}");
        sql.SET("PROF = #{record.prof,jdbcType=CHAR}");
        sql.SET("RETIREDATE = #{record.retiredate,jdbcType=CHAR}");
        sql.SET("SECRET_EMAIL = #{record.secretEmail,jdbcType=VARCHAR}");
        sql.SET("SHORTNAME = #{record.shortname,jdbcType=VARCHAR}");
        sql.SET("TITLETECHPOST = #{record.titletechpost,jdbcType=VARCHAR}");
        sql.SET("AGE = #{record.age,jdbcType=VARCHAR}");
        sql.SET("WORKAGE = #{record.workage,jdbcType=VARCHAR}");
        
        BdPsndocExample example = (BdPsndocExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BD_PSNDOC
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String updateByPrimaryKeySelective(BdPsndocWithBLOBs record) {
        SQL sql = new SQL();
        sql.UPDATE("BD_PSNDOC");
        
        if (record.getAddr() != null) {
            sql.SET("ADDR = #{addr,jdbcType=VARCHAR}");
        }
        
        if (record.getBirthdate() != null) {
            sql.SET("BIRTHDATE = #{birthdate,jdbcType=CHAR}");
        }
        
        if (record.getCode() != null) {
            sql.SET("CODE = #{code,jdbcType=VARCHAR}");
        }
        
        if (record.getCreationtime() != null) {
            sql.SET("CREATIONTIME = #{creationtime,jdbcType=CHAR}");
        }
        
        if (record.getCreator() != null) {
            sql.SET("CREATOR = #{creator,jdbcType=VARCHAR}");
        }
        
        if (record.getDataoriginflag() != null) {
            sql.SET("DATAORIGINFLAG = #{dataoriginflag,jdbcType=DECIMAL}");
        }
        
        if (record.getDef1() != null) {
            sql.SET("DEF1 = #{def1,jdbcType=VARCHAR}");
        }
        
        if (record.getDef10() != null) {
            sql.SET("DEF10 = #{def10,jdbcType=VARCHAR}");
        }
        
        if (record.getDef11() != null) {
            sql.SET("DEF11 = #{def11,jdbcType=VARCHAR}");
        }
        
        if (record.getDef12() != null) {
            sql.SET("DEF12 = #{def12,jdbcType=VARCHAR}");
        }
        
        if (record.getDef13() != null) {
            sql.SET("DEF13 = #{def13,jdbcType=VARCHAR}");
        }
        
        if (record.getDef14() != null) {
            sql.SET("DEF14 = #{def14,jdbcType=VARCHAR}");
        }
        
        if (record.getDef15() != null) {
            sql.SET("DEF15 = #{def15,jdbcType=VARCHAR}");
        }
        
        if (record.getDef16() != null) {
            sql.SET("DEF16 = #{def16,jdbcType=VARCHAR}");
        }
        
        if (record.getDef17() != null) {
            sql.SET("DEF17 = #{def17,jdbcType=VARCHAR}");
        }
        
        if (record.getDef18() != null) {
            sql.SET("DEF18 = #{def18,jdbcType=VARCHAR}");
        }
        
        if (record.getDef19() != null) {
            sql.SET("DEF19 = #{def19,jdbcType=VARCHAR}");
        }
        
        if (record.getDef2() != null) {
            sql.SET("DEF2 = #{def2,jdbcType=VARCHAR}");
        }
        
        if (record.getDef20() != null) {
            sql.SET("DEF20 = #{def20,jdbcType=VARCHAR}");
        }
        
        if (record.getDef3() != null) {
            sql.SET("DEF3 = #{def3,jdbcType=VARCHAR}");
        }
        
        if (record.getDef4() != null) {
            sql.SET("DEF4 = #{def4,jdbcType=VARCHAR}");
        }
        
        if (record.getDef5() != null) {
            sql.SET("DEF5 = #{def5,jdbcType=VARCHAR}");
        }
        
        if (record.getDef6() != null) {
            sql.SET("DEF6 = #{def6,jdbcType=VARCHAR}");
        }
        
        if (record.getDef7() != null) {
            sql.SET("DEF7 = #{def7,jdbcType=VARCHAR}");
        }
        
        if (record.getDef8() != null) {
            sql.SET("DEF8 = #{def8,jdbcType=VARCHAR}");
        }
        
        if (record.getDef9() != null) {
            sql.SET("DEF9 = #{def9,jdbcType=VARCHAR}");
        }
        
        if (record.getDr() != null) {
            sql.SET("DR = #{dr,jdbcType=DECIMAL}");
        }
        
        if (record.getEmail() != null) {
            sql.SET("EMAIL = #{email,jdbcType=VARCHAR}");
        }
        
        if (record.getEnablestate() != null) {
            sql.SET("ENABLESTATE = #{enablestate,jdbcType=DECIMAL}");
        }
        
        if (record.getFirstname() != null) {
            sql.SET("FIRSTNAME = #{firstname,jdbcType=VARCHAR}");
        }
        
        if (record.getHomephone() != null) {
            sql.SET("HOMEPHONE = #{homephone,jdbcType=VARCHAR}");
        }
        
        if (record.getId() != null) {
            sql.SET("ID = #{id,jdbcType=VARCHAR}");
        }
        
        if (record.getIdtype() != null) {
            sql.SET("IDTYPE = #{idtype,jdbcType=VARCHAR}");
        }
        
        if (record.getJoinworkdate() != null) {
            sql.SET("JOINWORKDATE = #{joinworkdate,jdbcType=CHAR}");
        }
        
        if (record.getLastname() != null) {
            sql.SET("LASTNAME = #{lastname,jdbcType=VARCHAR}");
        }
        
        if (record.getMnecode() != null) {
            sql.SET("MNECODE = #{mnecode,jdbcType=VARCHAR}");
        }
        
        if (record.getMobile() != null) {
            sql.SET("MOBILE = #{mobile,jdbcType=VARCHAR}");
        }
        
        if (record.getModifiedtime() != null) {
            sql.SET("MODIFIEDTIME = #{modifiedtime,jdbcType=CHAR}");
        }
        
        if (record.getModifier() != null) {
            sql.SET("MODIFIER = #{modifier,jdbcType=VARCHAR}");
        }
        
        if (record.getName() != null) {
            sql.SET("NAME = #{name,jdbcType=VARCHAR}");
        }
        
        if (record.getName2() != null) {
            sql.SET("NAME2 = #{name2,jdbcType=VARCHAR}");
        }
        
        if (record.getName3() != null) {
            sql.SET("NAME3 = #{name3,jdbcType=VARCHAR}");
        }
        
        if (record.getName4() != null) {
            sql.SET("NAME4 = #{name4,jdbcType=VARCHAR}");
        }
        
        if (record.getName5() != null) {
            sql.SET("NAME5 = #{name5,jdbcType=VARCHAR}");
        }
        
        if (record.getName6() != null) {
            sql.SET("NAME6 = #{name6,jdbcType=VARCHAR}");
        }
        
        if (record.getNickname() != null) {
            sql.SET("NICKNAME = #{nickname,jdbcType=VARCHAR}");
        }
        
        if (record.getOfficephone() != null) {
            sql.SET("OFFICEPHONE = #{officephone,jdbcType=VARCHAR}");
        }
        
        if (record.getPkGroup() != null) {
            sql.SET("PK_GROUP = #{pkGroup,jdbcType=VARCHAR}");
        }
        
        if (record.getPkOrg() != null) {
            sql.SET("PK_ORG = #{pkOrg,jdbcType=VARCHAR}");
        }
        
        if (record.getSex() != null) {
            sql.SET("SEX = #{sex,jdbcType=DECIMAL}");
        }
        
        if (record.getTs() != null) {
            sql.SET("TS = #{ts,jdbcType=CHAR}");
        }
        
        if (record.getUsedname() != null) {
            sql.SET("USEDNAME = #{usedname,jdbcType=VARCHAR}");
        }
        
        if (record.getIsshopassist() != null) {
            sql.SET("ISSHOPASSIST = #{isshopassist,jdbcType=CHAR}");
        }
        
        if (record.getBloodtype() != null) {
            sql.SET("BLOODTYPE = #{bloodtype,jdbcType=VARCHAR}");
        }
        
        if (record.getCensusaddr() != null) {
            sql.SET("CENSUSADDR = #{censusaddr,jdbcType=VARCHAR}");
        }
        
        if (record.getCharacterrpr() != null) {
            sql.SET("CHARACTERRPR = #{characterrpr,jdbcType=VARCHAR}");
        }
        
        if (record.getCountry() != null) {
            sql.SET("COUNTRY = #{country,jdbcType=VARCHAR}");
        }
        
        if (record.getDieDate() != null) {
            sql.SET("DIE_DATE = #{dieDate,jdbcType=CHAR}");
        }
        
        if (record.getDieRemark() != null) {
            sql.SET("DIE_REMARK = #{dieRemark,jdbcType=VARCHAR}");
        }
        
        if (record.getEdu() != null) {
            sql.SET("EDU = #{edu,jdbcType=VARCHAR}");
        }
        
        if (record.getFax() != null) {
            sql.SET("FAX = #{fax,jdbcType=VARCHAR}");
        }
        
        if (record.getFileaddress() != null) {
            sql.SET("FILEADDRESS = #{fileaddress,jdbcType=VARCHAR}");
        }
        
        if (record.getHealth() != null) {
            sql.SET("HEALTH = #{health,jdbcType=VARCHAR}");
        }
        
        if (record.getIscadre() != null) {
            sql.SET("ISCADRE = #{iscadre,jdbcType=CHAR}");
        }
        
        if (record.getIshiskeypsn() != null) {
            sql.SET("ISHISKEYPSN = #{ishiskeypsn,jdbcType=CHAR}");
        }
        
        if (record.getIshisleader() != null) {
            sql.SET("ISHISLEADER = #{ishisleader,jdbcType=CHAR}");
        }
        
        if (record.getJoinpolitydate() != null) {
            sql.SET("JOINPOLITYDATE = #{joinpolitydate,jdbcType=CHAR}");
        }
        
        if (record.getMarital() != null) {
            sql.SET("MARITAL = #{marital,jdbcType=VARCHAR}");
        }
        
        if (record.getMarriagedate() != null) {
            sql.SET("MARRIAGEDATE = #{marriagedate,jdbcType=CHAR}");
        }
        
        if (record.getNationality() != null) {
            sql.SET("NATIONALITY = #{nationality,jdbcType=VARCHAR}");
        }
        
        if (record.getNativeplace() != null) {
            sql.SET("NATIVEPLACE = #{nativeplace,jdbcType=VARCHAR}");
        }
        
        if (record.getPenelauth() != null) {
            sql.SET("PENELAUTH = #{penelauth,jdbcType=VARCHAR}");
        }
        
        if (record.getPermanreside() != null) {
            sql.SET("PERMANRESIDE = #{permanreside,jdbcType=VARCHAR}");
        }
        
        if (record.getPkDegree() != null) {
            sql.SET("PK_DEGREE = #{pkDegree,jdbcType=VARCHAR}");
        }
        
        if (record.getPkHrorg() != null) {
            sql.SET("PK_HRORG = #{pkHrorg,jdbcType=VARCHAR}");
        }
        
        if (record.getPolity() != null) {
            sql.SET("POLITY = #{polity,jdbcType=VARCHAR}");
        }
        
        if (record.getPostalcode() != null) {
            sql.SET("POSTALCODE = #{postalcode,jdbcType=VARCHAR}");
        }
        
        if (record.getProf() != null) {
            sql.SET("PROF = #{prof,jdbcType=CHAR}");
        }
        
        if (record.getRetiredate() != null) {
            sql.SET("RETIREDATE = #{retiredate,jdbcType=CHAR}");
        }
        
        if (record.getSecretEmail() != null) {
            sql.SET("SECRET_EMAIL = #{secretEmail,jdbcType=VARCHAR}");
        }
        
        if (record.getShortname() != null) {
            sql.SET("SHORTNAME = #{shortname,jdbcType=VARCHAR}");
        }
        
        if (record.getTitletechpost() != null) {
            sql.SET("TITLETECHPOST = #{titletechpost,jdbcType=VARCHAR}");
        }
        
        if (record.getAge() != null) {
            sql.SET("AGE = #{age,jdbcType=VARCHAR}");
        }
        
        if (record.getWorkage() != null) {
            sql.SET("WORKAGE = #{workage,jdbcType=VARCHAR}");
        }
        
        if (record.getPhoto() != null) {
            sql.SET("PHOTO = #{photo,jdbcType=BLOB}");
        }
        
        if (record.getPreviewphoto() != null) {
            sql.SET("PREVIEWPHOTO = #{previewphoto,jdbcType=BLOB}");
        }
        
        sql.WHERE("PK_PSNDOC = #{pkPsndoc,jdbcType=CHAR}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BD_PSNDOC
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    protected void applyWhere(SQL sql, BdPsndocExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}