package com.example.webredis.data;

import java.math.BigDecimal;

public class BdPsndoc {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.PK_PSNDOC
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String pkPsndoc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.ADDR
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String addr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.BIRTHDATE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String birthdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.CODE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.CREATIONTIME
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String creationtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.CREATOR
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.DATAORIGINFLAG
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private BigDecimal dataoriginflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.DEF1
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String def1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.DEF10
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String def10;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.DEF11
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String def11;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.DEF12
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String def12;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.DEF13
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String def13;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.DEF14
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String def14;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.DEF15
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String def15;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.DEF16
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String def16;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.DEF17
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String def17;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.DEF18
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String def18;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.DEF19
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String def19;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.DEF2
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String def2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.DEF20
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String def20;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.DEF3
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String def3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.DEF4
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String def4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.DEF5
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String def5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.DEF6
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String def6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.DEF7
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String def7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.DEF8
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String def8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.DEF9
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String def9;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.DR
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private Long dr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.EMAIL
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.ENABLESTATE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private BigDecimal enablestate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.FIRSTNAME
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String firstname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.HOMEPHONE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String homephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.ID
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.IDTYPE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String idtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.JOINWORKDATE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String joinworkdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.LASTNAME
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String lastname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.MNECODE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String mnecode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.MOBILE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.MODIFIEDTIME
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String modifiedtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.MODIFIER
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.NAME
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.NAME2
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String name2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.NAME3
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String name3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.NAME4
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String name4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.NAME5
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String name5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.NAME6
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String name6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.NICKNAME
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.OFFICEPHONE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String officephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.PK_GROUP
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String pkGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.PK_ORG
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String pkOrg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.SEX
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private BigDecimal sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.TS
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String ts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.USEDNAME
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String usedname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.ISSHOPASSIST
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String isshopassist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.BLOODTYPE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String bloodtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.CENSUSADDR
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String censusaddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.CHARACTERRPR
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String characterrpr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.COUNTRY
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.DIE_DATE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String dieDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.DIE_REMARK
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String dieRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.EDU
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String edu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.FAX
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String fax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.FILEADDRESS
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String fileaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.HEALTH
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String health;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.ISCADRE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String iscadre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.ISHISKEYPSN
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String ishiskeypsn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.ISHISLEADER
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String ishisleader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.JOINPOLITYDATE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String joinpolitydate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.MARITAL
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String marital;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.MARRIAGEDATE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String marriagedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.NATIONALITY
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String nationality;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.NATIVEPLACE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String nativeplace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.PENELAUTH
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String penelauth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.PERMANRESIDE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String permanreside;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.PK_DEGREE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String pkDegree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.PK_HRORG
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String pkHrorg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.POLITY
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String polity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.POSTALCODE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String postalcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.PROF
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String prof;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.RETIREDATE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String retiredate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.SECRET_EMAIL
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String secretEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.SHORTNAME
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String shortname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.TITLETECHPOST
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String titletechpost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.AGE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.WORKAGE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private String workage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.PK_PSNDOC
     *
     * @return the value of BD_PSNDOC.PK_PSNDOC
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getPkPsndoc() {
        return pkPsndoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.PK_PSNDOC
     *
     * @param pkPsndoc the value for BD_PSNDOC.PK_PSNDOC
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setPkPsndoc(String pkPsndoc) {
        this.pkPsndoc = pkPsndoc == null ? null : pkPsndoc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.ADDR
     *
     * @return the value of BD_PSNDOC.ADDR
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.ADDR
     *
     * @param addr the value for BD_PSNDOC.ADDR
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.BIRTHDATE
     *
     * @return the value of BD_PSNDOC.BIRTHDATE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getBirthdate() {
        return birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.BIRTHDATE
     *
     * @param birthdate the value for BD_PSNDOC.BIRTHDATE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setBirthdate(String birthdate) {
        this.birthdate = birthdate == null ? null : birthdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.CODE
     *
     * @return the value of BD_PSNDOC.CODE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.CODE
     *
     * @param code the value for BD_PSNDOC.CODE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.CREATIONTIME
     *
     * @return the value of BD_PSNDOC.CREATIONTIME
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getCreationtime() {
        return creationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.CREATIONTIME
     *
     * @param creationtime the value for BD_PSNDOC.CREATIONTIME
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setCreationtime(String creationtime) {
        this.creationtime = creationtime == null ? null : creationtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.CREATOR
     *
     * @return the value of BD_PSNDOC.CREATOR
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.CREATOR
     *
     * @param creator the value for BD_PSNDOC.CREATOR
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.DATAORIGINFLAG
     *
     * @return the value of BD_PSNDOC.DATAORIGINFLAG
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public BigDecimal getDataoriginflag() {
        return dataoriginflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.DATAORIGINFLAG
     *
     * @param dataoriginflag the value for BD_PSNDOC.DATAORIGINFLAG
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setDataoriginflag(BigDecimal dataoriginflag) {
        this.dataoriginflag = dataoriginflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.DEF1
     *
     * @return the value of BD_PSNDOC.DEF1
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getDef1() {
        return def1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.DEF1
     *
     * @param def1 the value for BD_PSNDOC.DEF1
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setDef1(String def1) {
        this.def1 = def1 == null ? null : def1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.DEF10
     *
     * @return the value of BD_PSNDOC.DEF10
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getDef10() {
        return def10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.DEF10
     *
     * @param def10 the value for BD_PSNDOC.DEF10
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setDef10(String def10) {
        this.def10 = def10 == null ? null : def10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.DEF11
     *
     * @return the value of BD_PSNDOC.DEF11
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getDef11() {
        return def11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.DEF11
     *
     * @param def11 the value for BD_PSNDOC.DEF11
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setDef11(String def11) {
        this.def11 = def11 == null ? null : def11.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.DEF12
     *
     * @return the value of BD_PSNDOC.DEF12
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getDef12() {
        return def12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.DEF12
     *
     * @param def12 the value for BD_PSNDOC.DEF12
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setDef12(String def12) {
        this.def12 = def12 == null ? null : def12.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.DEF13
     *
     * @return the value of BD_PSNDOC.DEF13
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getDef13() {
        return def13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.DEF13
     *
     * @param def13 the value for BD_PSNDOC.DEF13
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setDef13(String def13) {
        this.def13 = def13 == null ? null : def13.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.DEF14
     *
     * @return the value of BD_PSNDOC.DEF14
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getDef14() {
        return def14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.DEF14
     *
     * @param def14 the value for BD_PSNDOC.DEF14
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setDef14(String def14) {
        this.def14 = def14 == null ? null : def14.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.DEF15
     *
     * @return the value of BD_PSNDOC.DEF15
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getDef15() {
        return def15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.DEF15
     *
     * @param def15 the value for BD_PSNDOC.DEF15
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setDef15(String def15) {
        this.def15 = def15 == null ? null : def15.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.DEF16
     *
     * @return the value of BD_PSNDOC.DEF16
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getDef16() {
        return def16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.DEF16
     *
     * @param def16 the value for BD_PSNDOC.DEF16
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setDef16(String def16) {
        this.def16 = def16 == null ? null : def16.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.DEF17
     *
     * @return the value of BD_PSNDOC.DEF17
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getDef17() {
        return def17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.DEF17
     *
     * @param def17 the value for BD_PSNDOC.DEF17
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setDef17(String def17) {
        this.def17 = def17 == null ? null : def17.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.DEF18
     *
     * @return the value of BD_PSNDOC.DEF18
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getDef18() {
        return def18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.DEF18
     *
     * @param def18 the value for BD_PSNDOC.DEF18
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setDef18(String def18) {
        this.def18 = def18 == null ? null : def18.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.DEF19
     *
     * @return the value of BD_PSNDOC.DEF19
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getDef19() {
        return def19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.DEF19
     *
     * @param def19 the value for BD_PSNDOC.DEF19
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setDef19(String def19) {
        this.def19 = def19 == null ? null : def19.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.DEF2
     *
     * @return the value of BD_PSNDOC.DEF2
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getDef2() {
        return def2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.DEF2
     *
     * @param def2 the value for BD_PSNDOC.DEF2
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setDef2(String def2) {
        this.def2 = def2 == null ? null : def2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.DEF20
     *
     * @return the value of BD_PSNDOC.DEF20
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getDef20() {
        return def20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.DEF20
     *
     * @param def20 the value for BD_PSNDOC.DEF20
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setDef20(String def20) {
        this.def20 = def20 == null ? null : def20.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.DEF3
     *
     * @return the value of BD_PSNDOC.DEF3
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getDef3() {
        return def3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.DEF3
     *
     * @param def3 the value for BD_PSNDOC.DEF3
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setDef3(String def3) {
        this.def3 = def3 == null ? null : def3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.DEF4
     *
     * @return the value of BD_PSNDOC.DEF4
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getDef4() {
        return def4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.DEF4
     *
     * @param def4 the value for BD_PSNDOC.DEF4
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setDef4(String def4) {
        this.def4 = def4 == null ? null : def4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.DEF5
     *
     * @return the value of BD_PSNDOC.DEF5
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getDef5() {
        return def5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.DEF5
     *
     * @param def5 the value for BD_PSNDOC.DEF5
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setDef5(String def5) {
        this.def5 = def5 == null ? null : def5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.DEF6
     *
     * @return the value of BD_PSNDOC.DEF6
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getDef6() {
        return def6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.DEF6
     *
     * @param def6 the value for BD_PSNDOC.DEF6
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setDef6(String def6) {
        this.def6 = def6 == null ? null : def6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.DEF7
     *
     * @return the value of BD_PSNDOC.DEF7
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getDef7() {
        return def7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.DEF7
     *
     * @param def7 the value for BD_PSNDOC.DEF7
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setDef7(String def7) {
        this.def7 = def7 == null ? null : def7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.DEF8
     *
     * @return the value of BD_PSNDOC.DEF8
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getDef8() {
        return def8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.DEF8
     *
     * @param def8 the value for BD_PSNDOC.DEF8
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setDef8(String def8) {
        this.def8 = def8 == null ? null : def8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.DEF9
     *
     * @return the value of BD_PSNDOC.DEF9
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getDef9() {
        return def9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.DEF9
     *
     * @param def9 the value for BD_PSNDOC.DEF9
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setDef9(String def9) {
        this.def9 = def9 == null ? null : def9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.DR
     *
     * @return the value of BD_PSNDOC.DR
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public Long getDr() {
        return dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.DR
     *
     * @param dr the value for BD_PSNDOC.DR
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setDr(Long dr) {
        this.dr = dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.EMAIL
     *
     * @return the value of BD_PSNDOC.EMAIL
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.EMAIL
     *
     * @param email the value for BD_PSNDOC.EMAIL
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.ENABLESTATE
     *
     * @return the value of BD_PSNDOC.ENABLESTATE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public BigDecimal getEnablestate() {
        return enablestate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.ENABLESTATE
     *
     * @param enablestate the value for BD_PSNDOC.ENABLESTATE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setEnablestate(BigDecimal enablestate) {
        this.enablestate = enablestate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.FIRSTNAME
     *
     * @return the value of BD_PSNDOC.FIRSTNAME
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getFirstname() {
        return firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.FIRSTNAME
     *
     * @param firstname the value for BD_PSNDOC.FIRSTNAME
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setFirstname(String firstname) {
        this.firstname = firstname == null ? null : firstname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.HOMEPHONE
     *
     * @return the value of BD_PSNDOC.HOMEPHONE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getHomephone() {
        return homephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.HOMEPHONE
     *
     * @param homephone the value for BD_PSNDOC.HOMEPHONE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setHomephone(String homephone) {
        this.homephone = homephone == null ? null : homephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.ID
     *
     * @return the value of BD_PSNDOC.ID
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.ID
     *
     * @param id the value for BD_PSNDOC.ID
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.IDTYPE
     *
     * @return the value of BD_PSNDOC.IDTYPE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getIdtype() {
        return idtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.IDTYPE
     *
     * @param idtype the value for BD_PSNDOC.IDTYPE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setIdtype(String idtype) {
        this.idtype = idtype == null ? null : idtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.JOINWORKDATE
     *
     * @return the value of BD_PSNDOC.JOINWORKDATE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getJoinworkdate() {
        return joinworkdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.JOINWORKDATE
     *
     * @param joinworkdate the value for BD_PSNDOC.JOINWORKDATE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setJoinworkdate(String joinworkdate) {
        this.joinworkdate = joinworkdate == null ? null : joinworkdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.LASTNAME
     *
     * @return the value of BD_PSNDOC.LASTNAME
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.LASTNAME
     *
     * @param lastname the value for BD_PSNDOC.LASTNAME
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setLastname(String lastname) {
        this.lastname = lastname == null ? null : lastname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.MNECODE
     *
     * @return the value of BD_PSNDOC.MNECODE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getMnecode() {
        return mnecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.MNECODE
     *
     * @param mnecode the value for BD_PSNDOC.MNECODE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setMnecode(String mnecode) {
        this.mnecode = mnecode == null ? null : mnecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.MOBILE
     *
     * @return the value of BD_PSNDOC.MOBILE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.MOBILE
     *
     * @param mobile the value for BD_PSNDOC.MOBILE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.MODIFIEDTIME
     *
     * @return the value of BD_PSNDOC.MODIFIEDTIME
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getModifiedtime() {
        return modifiedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.MODIFIEDTIME
     *
     * @param modifiedtime the value for BD_PSNDOC.MODIFIEDTIME
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setModifiedtime(String modifiedtime) {
        this.modifiedtime = modifiedtime == null ? null : modifiedtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.MODIFIER
     *
     * @return the value of BD_PSNDOC.MODIFIER
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.MODIFIER
     *
     * @param modifier the value for BD_PSNDOC.MODIFIER
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.NAME
     *
     * @return the value of BD_PSNDOC.NAME
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.NAME
     *
     * @param name the value for BD_PSNDOC.NAME
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.NAME2
     *
     * @return the value of BD_PSNDOC.NAME2
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getName2() {
        return name2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.NAME2
     *
     * @param name2 the value for BD_PSNDOC.NAME2
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setName2(String name2) {
        this.name2 = name2 == null ? null : name2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.NAME3
     *
     * @return the value of BD_PSNDOC.NAME3
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getName3() {
        return name3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.NAME3
     *
     * @param name3 the value for BD_PSNDOC.NAME3
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setName3(String name3) {
        this.name3 = name3 == null ? null : name3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.NAME4
     *
     * @return the value of BD_PSNDOC.NAME4
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getName4() {
        return name4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.NAME4
     *
     * @param name4 the value for BD_PSNDOC.NAME4
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setName4(String name4) {
        this.name4 = name4 == null ? null : name4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.NAME5
     *
     * @return the value of BD_PSNDOC.NAME5
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getName5() {
        return name5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.NAME5
     *
     * @param name5 the value for BD_PSNDOC.NAME5
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setName5(String name5) {
        this.name5 = name5 == null ? null : name5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.NAME6
     *
     * @return the value of BD_PSNDOC.NAME6
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getName6() {
        return name6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.NAME6
     *
     * @param name6 the value for BD_PSNDOC.NAME6
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setName6(String name6) {
        this.name6 = name6 == null ? null : name6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.NICKNAME
     *
     * @return the value of BD_PSNDOC.NICKNAME
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.NICKNAME
     *
     * @param nickname the value for BD_PSNDOC.NICKNAME
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.OFFICEPHONE
     *
     * @return the value of BD_PSNDOC.OFFICEPHONE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getOfficephone() {
        return officephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.OFFICEPHONE
     *
     * @param officephone the value for BD_PSNDOC.OFFICEPHONE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setOfficephone(String officephone) {
        this.officephone = officephone == null ? null : officephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.PK_GROUP
     *
     * @return the value of BD_PSNDOC.PK_GROUP
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getPkGroup() {
        return pkGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.PK_GROUP
     *
     * @param pkGroup the value for BD_PSNDOC.PK_GROUP
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setPkGroup(String pkGroup) {
        this.pkGroup = pkGroup == null ? null : pkGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.PK_ORG
     *
     * @return the value of BD_PSNDOC.PK_ORG
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getPkOrg() {
        return pkOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.PK_ORG
     *
     * @param pkOrg the value for BD_PSNDOC.PK_ORG
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setPkOrg(String pkOrg) {
        this.pkOrg = pkOrg == null ? null : pkOrg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.SEX
     *
     * @return the value of BD_PSNDOC.SEX
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public BigDecimal getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.SEX
     *
     * @param sex the value for BD_PSNDOC.SEX
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setSex(BigDecimal sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.TS
     *
     * @return the value of BD_PSNDOC.TS
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.TS
     *
     * @param ts the value for BD_PSNDOC.TS
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setTs(String ts) {
        this.ts = ts == null ? null : ts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.USEDNAME
     *
     * @return the value of BD_PSNDOC.USEDNAME
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getUsedname() {
        return usedname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.USEDNAME
     *
     * @param usedname the value for BD_PSNDOC.USEDNAME
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setUsedname(String usedname) {
        this.usedname = usedname == null ? null : usedname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.ISSHOPASSIST
     *
     * @return the value of BD_PSNDOC.ISSHOPASSIST
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getIsshopassist() {
        return isshopassist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.ISSHOPASSIST
     *
     * @param isshopassist the value for BD_PSNDOC.ISSHOPASSIST
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setIsshopassist(String isshopassist) {
        this.isshopassist = isshopassist == null ? null : isshopassist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.BLOODTYPE
     *
     * @return the value of BD_PSNDOC.BLOODTYPE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getBloodtype() {
        return bloodtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.BLOODTYPE
     *
     * @param bloodtype the value for BD_PSNDOC.BLOODTYPE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setBloodtype(String bloodtype) {
        this.bloodtype = bloodtype == null ? null : bloodtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.CENSUSADDR
     *
     * @return the value of BD_PSNDOC.CENSUSADDR
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getCensusaddr() {
        return censusaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.CENSUSADDR
     *
     * @param censusaddr the value for BD_PSNDOC.CENSUSADDR
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setCensusaddr(String censusaddr) {
        this.censusaddr = censusaddr == null ? null : censusaddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.CHARACTERRPR
     *
     * @return the value of BD_PSNDOC.CHARACTERRPR
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getCharacterrpr() {
        return characterrpr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.CHARACTERRPR
     *
     * @param characterrpr the value for BD_PSNDOC.CHARACTERRPR
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setCharacterrpr(String characterrpr) {
        this.characterrpr = characterrpr == null ? null : characterrpr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.COUNTRY
     *
     * @return the value of BD_PSNDOC.COUNTRY
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.COUNTRY
     *
     * @param country the value for BD_PSNDOC.COUNTRY
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.DIE_DATE
     *
     * @return the value of BD_PSNDOC.DIE_DATE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getDieDate() {
        return dieDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.DIE_DATE
     *
     * @param dieDate the value for BD_PSNDOC.DIE_DATE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setDieDate(String dieDate) {
        this.dieDate = dieDate == null ? null : dieDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.DIE_REMARK
     *
     * @return the value of BD_PSNDOC.DIE_REMARK
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getDieRemark() {
        return dieRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.DIE_REMARK
     *
     * @param dieRemark the value for BD_PSNDOC.DIE_REMARK
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setDieRemark(String dieRemark) {
        this.dieRemark = dieRemark == null ? null : dieRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.EDU
     *
     * @return the value of BD_PSNDOC.EDU
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getEdu() {
        return edu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.EDU
     *
     * @param edu the value for BD_PSNDOC.EDU
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setEdu(String edu) {
        this.edu = edu == null ? null : edu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.FAX
     *
     * @return the value of BD_PSNDOC.FAX
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.FAX
     *
     * @param fax the value for BD_PSNDOC.FAX
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.FILEADDRESS
     *
     * @return the value of BD_PSNDOC.FILEADDRESS
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getFileaddress() {
        return fileaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.FILEADDRESS
     *
     * @param fileaddress the value for BD_PSNDOC.FILEADDRESS
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setFileaddress(String fileaddress) {
        this.fileaddress = fileaddress == null ? null : fileaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.HEALTH
     *
     * @return the value of BD_PSNDOC.HEALTH
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getHealth() {
        return health;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.HEALTH
     *
     * @param health the value for BD_PSNDOC.HEALTH
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setHealth(String health) {
        this.health = health == null ? null : health.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.ISCADRE
     *
     * @return the value of BD_PSNDOC.ISCADRE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getIscadre() {
        return iscadre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.ISCADRE
     *
     * @param iscadre the value for BD_PSNDOC.ISCADRE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setIscadre(String iscadre) {
        this.iscadre = iscadre == null ? null : iscadre.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.ISHISKEYPSN
     *
     * @return the value of BD_PSNDOC.ISHISKEYPSN
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getIshiskeypsn() {
        return ishiskeypsn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.ISHISKEYPSN
     *
     * @param ishiskeypsn the value for BD_PSNDOC.ISHISKEYPSN
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setIshiskeypsn(String ishiskeypsn) {
        this.ishiskeypsn = ishiskeypsn == null ? null : ishiskeypsn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.ISHISLEADER
     *
     * @return the value of BD_PSNDOC.ISHISLEADER
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getIshisleader() {
        return ishisleader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.ISHISLEADER
     *
     * @param ishisleader the value for BD_PSNDOC.ISHISLEADER
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setIshisleader(String ishisleader) {
        this.ishisleader = ishisleader == null ? null : ishisleader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.JOINPOLITYDATE
     *
     * @return the value of BD_PSNDOC.JOINPOLITYDATE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getJoinpolitydate() {
        return joinpolitydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.JOINPOLITYDATE
     *
     * @param joinpolitydate the value for BD_PSNDOC.JOINPOLITYDATE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setJoinpolitydate(String joinpolitydate) {
        this.joinpolitydate = joinpolitydate == null ? null : joinpolitydate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.MARITAL
     *
     * @return the value of BD_PSNDOC.MARITAL
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getMarital() {
        return marital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.MARITAL
     *
     * @param marital the value for BD_PSNDOC.MARITAL
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setMarital(String marital) {
        this.marital = marital == null ? null : marital.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.MARRIAGEDATE
     *
     * @return the value of BD_PSNDOC.MARRIAGEDATE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getMarriagedate() {
        return marriagedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.MARRIAGEDATE
     *
     * @param marriagedate the value for BD_PSNDOC.MARRIAGEDATE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setMarriagedate(String marriagedate) {
        this.marriagedate = marriagedate == null ? null : marriagedate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.NATIONALITY
     *
     * @return the value of BD_PSNDOC.NATIONALITY
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.NATIONALITY
     *
     * @param nationality the value for BD_PSNDOC.NATIONALITY
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setNationality(String nationality) {
        this.nationality = nationality == null ? null : nationality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.NATIVEPLACE
     *
     * @return the value of BD_PSNDOC.NATIVEPLACE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getNativeplace() {
        return nativeplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.NATIVEPLACE
     *
     * @param nativeplace the value for BD_PSNDOC.NATIVEPLACE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setNativeplace(String nativeplace) {
        this.nativeplace = nativeplace == null ? null : nativeplace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.PENELAUTH
     *
     * @return the value of BD_PSNDOC.PENELAUTH
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getPenelauth() {
        return penelauth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.PENELAUTH
     *
     * @param penelauth the value for BD_PSNDOC.PENELAUTH
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setPenelauth(String penelauth) {
        this.penelauth = penelauth == null ? null : penelauth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.PERMANRESIDE
     *
     * @return the value of BD_PSNDOC.PERMANRESIDE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getPermanreside() {
        return permanreside;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.PERMANRESIDE
     *
     * @param permanreside the value for BD_PSNDOC.PERMANRESIDE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setPermanreside(String permanreside) {
        this.permanreside = permanreside == null ? null : permanreside.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.PK_DEGREE
     *
     * @return the value of BD_PSNDOC.PK_DEGREE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getPkDegree() {
        return pkDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.PK_DEGREE
     *
     * @param pkDegree the value for BD_PSNDOC.PK_DEGREE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setPkDegree(String pkDegree) {
        this.pkDegree = pkDegree == null ? null : pkDegree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.PK_HRORG
     *
     * @return the value of BD_PSNDOC.PK_HRORG
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getPkHrorg() {
        return pkHrorg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.PK_HRORG
     *
     * @param pkHrorg the value for BD_PSNDOC.PK_HRORG
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setPkHrorg(String pkHrorg) {
        this.pkHrorg = pkHrorg == null ? null : pkHrorg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.POLITY
     *
     * @return the value of BD_PSNDOC.POLITY
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getPolity() {
        return polity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.POLITY
     *
     * @param polity the value for BD_PSNDOC.POLITY
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setPolity(String polity) {
        this.polity = polity == null ? null : polity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.POSTALCODE
     *
     * @return the value of BD_PSNDOC.POSTALCODE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getPostalcode() {
        return postalcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.POSTALCODE
     *
     * @param postalcode the value for BD_PSNDOC.POSTALCODE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setPostalcode(String postalcode) {
        this.postalcode = postalcode == null ? null : postalcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.PROF
     *
     * @return the value of BD_PSNDOC.PROF
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getProf() {
        return prof;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.PROF
     *
     * @param prof the value for BD_PSNDOC.PROF
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setProf(String prof) {
        this.prof = prof == null ? null : prof.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.RETIREDATE
     *
     * @return the value of BD_PSNDOC.RETIREDATE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getRetiredate() {
        return retiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.RETIREDATE
     *
     * @param retiredate the value for BD_PSNDOC.RETIREDATE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setRetiredate(String retiredate) {
        this.retiredate = retiredate == null ? null : retiredate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.SECRET_EMAIL
     *
     * @return the value of BD_PSNDOC.SECRET_EMAIL
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getSecretEmail() {
        return secretEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.SECRET_EMAIL
     *
     * @param secretEmail the value for BD_PSNDOC.SECRET_EMAIL
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setSecretEmail(String secretEmail) {
        this.secretEmail = secretEmail == null ? null : secretEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.SHORTNAME
     *
     * @return the value of BD_PSNDOC.SHORTNAME
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getShortname() {
        return shortname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.SHORTNAME
     *
     * @param shortname the value for BD_PSNDOC.SHORTNAME
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setShortname(String shortname) {
        this.shortname = shortname == null ? null : shortname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.TITLETECHPOST
     *
     * @return the value of BD_PSNDOC.TITLETECHPOST
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getTitletechpost() {
        return titletechpost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.TITLETECHPOST
     *
     * @param titletechpost the value for BD_PSNDOC.TITLETECHPOST
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setTitletechpost(String titletechpost) {
        this.titletechpost = titletechpost == null ? null : titletechpost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.AGE
     *
     * @return the value of BD_PSNDOC.AGE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.AGE
     *
     * @param age the value for BD_PSNDOC.AGE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setAge(String age) {
        this.age = age == null ? null : age.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.WORKAGE
     *
     * @return the value of BD_PSNDOC.WORKAGE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public String getWorkage() {
        return workage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.WORKAGE
     *
     * @param workage the value for BD_PSNDOC.WORKAGE
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setWorkage(String workage) {
        this.workage = workage == null ? null : workage.trim();
    }
}