package com.example.webredis.data;

public class BdPsndocWithBLOBs extends BdPsndoc {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.PHOTO
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private byte[] photo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD_PSNDOC.PREVIEWPHOTO
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    private byte[] previewphoto;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.PHOTO
     *
     * @return the value of BD_PSNDOC.PHOTO
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public byte[] getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.PHOTO
     *
     * @param photo the value for BD_PSNDOC.PHOTO
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD_PSNDOC.PREVIEWPHOTO
     *
     * @return the value of BD_PSNDOC.PREVIEWPHOTO
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public byte[] getPreviewphoto() {
        return previewphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD_PSNDOC.PREVIEWPHOTO
     *
     * @param previewphoto the value for BD_PSNDOC.PREVIEWPHOTO
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    public void setPreviewphoto(byte[] previewphoto) {
        this.previewphoto = previewphoto;
    }
}