package com.example.webredis.data;

import com.example.webredis.data.BdPsndoc;
import com.example.webredis.data.BdPsndocExample;
import com.example.webredis.data.BdPsndocWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface BdPsndocMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BD_PSNDOC
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    @SelectProvider(type=BdPsndocSqlProvider.class, method="countByExample")
    long countByExample(BdPsndocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BD_PSNDOC
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    @DeleteProvider(type=BdPsndocSqlProvider.class, method="deleteByExample")
    int deleteByExample(BdPsndocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BD_PSNDOC
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    @Delete({
        "delete from BD_PSNDOC",
        "where PK_PSNDOC = #{pkPsndoc,jdbcType=CHAR}"
    })
    int deleteByPrimaryKey(String pkPsndoc);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BD_PSNDOC
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    @Insert({
        "insert into BD_PSNDOC (PK_PSNDOC, ADDR, ",
        "BIRTHDATE, CODE, CREATIONTIME, ",
        "CREATOR, DATAORIGINFLAG, ",
        "DEF1, DEF10, DEF11, ",
        "DEF12, DEF13, DEF14, ",
        "DEF15, DEF16, DEF17, ",
        "DEF18, DEF19, DEF2, ",
        "DEF20, DEF3, DEF4, ",
        "DEF5, DEF6, DEF7, ",
        "DEF8, DEF9, DR, ",
        "EMAIL, ENABLESTATE, ",
        "FIRSTNAME, HOMEPHONE, ",
        "ID, IDTYPE, JOINWORKDATE, ",
        "LASTNAME, MNECODE, ",
        "MOBILE, MODIFIEDTIME, ",
        "MODIFIER, NAME, ",
        "NAME2, NAME3, NAME4, ",
        "NAME5, NAME6, NICKNAME, ",
        "OFFICEPHONE, PK_GROUP, ",
        "PK_ORG, SEX, TS, ",
        "USEDNAME, ISSHOPASSIST, ",
        "BLOODTYPE, CENSUSADDR, ",
        "CHARACTERRPR, COUNTRY, ",
        "DIE_DATE, DIE_REMARK, ",
        "EDU, FAX, FILEADDRESS, ",
        "HEALTH, ISCADRE, ISHISKEYPSN, ",
        "ISHISLEADER, JOINPOLITYDATE, ",
        "MARITAL, MARRIAGEDATE, ",
        "NATIONALITY, NATIVEPLACE, ",
        "PENELAUTH, PERMANRESIDE, ",
        "PK_DEGREE, PK_HRORG, ",
        "POLITY, POSTALCODE, ",
        "PROF, RETIREDATE, SECRET_EMAIL, ",
        "SHORTNAME, TITLETECHPOST, ",
        "AGE, WORKAGE, PHOTO, ",
        "PREVIEWPHOTO)",
        "values (#{pkPsndoc,jdbcType=CHAR}, #{addr,jdbcType=VARCHAR}, ",
        "#{birthdate,jdbcType=CHAR}, #{code,jdbcType=VARCHAR}, #{creationtime,jdbcType=CHAR}, ",
        "#{creator,jdbcType=VARCHAR}, #{dataoriginflag,jdbcType=DECIMAL}, ",
        "#{def1,jdbcType=VARCHAR}, #{def10,jdbcType=VARCHAR}, #{def11,jdbcType=VARCHAR}, ",
        "#{def12,jdbcType=VARCHAR}, #{def13,jdbcType=VARCHAR}, #{def14,jdbcType=VARCHAR}, ",
        "#{def15,jdbcType=VARCHAR}, #{def16,jdbcType=VARCHAR}, #{def17,jdbcType=VARCHAR}, ",
        "#{def18,jdbcType=VARCHAR}, #{def19,jdbcType=VARCHAR}, #{def2,jdbcType=VARCHAR}, ",
        "#{def20,jdbcType=VARCHAR}, #{def3,jdbcType=VARCHAR}, #{def4,jdbcType=VARCHAR}, ",
        "#{def5,jdbcType=VARCHAR}, #{def6,jdbcType=VARCHAR}, #{def7,jdbcType=VARCHAR}, ",
        "#{def8,jdbcType=VARCHAR}, #{def9,jdbcType=VARCHAR}, #{dr,jdbcType=DECIMAL}, ",
        "#{email,jdbcType=VARCHAR}, #{enablestate,jdbcType=DECIMAL}, ",
        "#{firstname,jdbcType=VARCHAR}, #{homephone,jdbcType=VARCHAR}, ",
        "#{id,jdbcType=VARCHAR}, #{idtype,jdbcType=VARCHAR}, #{joinworkdate,jdbcType=CHAR}, ",
        "#{lastname,jdbcType=VARCHAR}, #{mnecode,jdbcType=VARCHAR}, ",
        "#{mobile,jdbcType=VARCHAR}, #{modifiedtime,jdbcType=CHAR}, ",
        "#{modifier,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR}, ",
        "#{name2,jdbcType=VARCHAR}, #{name3,jdbcType=VARCHAR}, #{name4,jdbcType=VARCHAR}, ",
        "#{name5,jdbcType=VARCHAR}, #{name6,jdbcType=VARCHAR}, #{nickname,jdbcType=VARCHAR}, ",
        "#{officephone,jdbcType=VARCHAR}, #{pkGroup,jdbcType=VARCHAR}, ",
        "#{pkOrg,jdbcType=VARCHAR}, #{sex,jdbcType=DECIMAL}, #{ts,jdbcType=CHAR}, ",
        "#{usedname,jdbcType=VARCHAR}, #{isshopassist,jdbcType=CHAR}, ",
        "#{bloodtype,jdbcType=VARCHAR}, #{censusaddr,jdbcType=VARCHAR}, ",
        "#{characterrpr,jdbcType=VARCHAR}, #{country,jdbcType=VARCHAR}, ",
        "#{dieDate,jdbcType=CHAR}, #{dieRemark,jdbcType=VARCHAR}, ",
        "#{edu,jdbcType=VARCHAR}, #{fax,jdbcType=VARCHAR}, #{fileaddress,jdbcType=VARCHAR}, ",
        "#{health,jdbcType=VARCHAR}, #{iscadre,jdbcType=CHAR}, #{ishiskeypsn,jdbcType=CHAR}, ",
        "#{ishisleader,jdbcType=CHAR}, #{joinpolitydate,jdbcType=CHAR}, ",
        "#{marital,jdbcType=VARCHAR}, #{marriagedate,jdbcType=CHAR}, ",
        "#{nationality,jdbcType=VARCHAR}, #{nativeplace,jdbcType=VARCHAR}, ",
        "#{penelauth,jdbcType=VARCHAR}, #{permanreside,jdbcType=VARCHAR}, ",
        "#{pkDegree,jdbcType=VARCHAR}, #{pkHrorg,jdbcType=VARCHAR}, ",
        "#{polity,jdbcType=VARCHAR}, #{postalcode,jdbcType=VARCHAR}, ",
        "#{prof,jdbcType=CHAR}, #{retiredate,jdbcType=CHAR}, #{secretEmail,jdbcType=VARCHAR}, ",
        "#{shortname,jdbcType=VARCHAR}, #{titletechpost,jdbcType=VARCHAR}, ",
        "#{age,jdbcType=VARCHAR}, #{workage,jdbcType=VARCHAR}, #{photo,jdbcType=BLOB}, ",
        "#{previewphoto,jdbcType=BLOB})"
    })
    int insert(BdPsndocWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BD_PSNDOC
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    @InsertProvider(type=BdPsndocSqlProvider.class, method="insertSelective")
    int insertSelective(BdPsndocWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BD_PSNDOC
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    @SelectProvider(type=BdPsndocSqlProvider.class, method="selectByExampleWithBLOBs")
    @Results({
        @Result(column="PK_PSNDOC", property="pkPsndoc", jdbcType=JdbcType.CHAR, id=true),
        @Result(column="ADDR", property="addr", jdbcType=JdbcType.VARCHAR),
        @Result(column="BIRTHDATE", property="birthdate", jdbcType=JdbcType.CHAR),
        @Result(column="CODE", property="code", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATIONTIME", property="creationtime", jdbcType=JdbcType.CHAR),
        @Result(column="CREATOR", property="creator", jdbcType=JdbcType.VARCHAR),
        @Result(column="DATAORIGINFLAG", property="dataoriginflag", jdbcType=JdbcType.DECIMAL),
        @Result(column="DEF1", property="def1", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF10", property="def10", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF11", property="def11", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF12", property="def12", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF13", property="def13", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF14", property="def14", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF15", property="def15", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF16", property="def16", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF17", property="def17", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF18", property="def18", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF19", property="def19", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF2", property="def2", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF20", property="def20", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF3", property="def3", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF4", property="def4", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF5", property="def5", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF6", property="def6", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF7", property="def7", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF8", property="def8", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF9", property="def9", jdbcType=JdbcType.VARCHAR),
        @Result(column="DR", property="dr", jdbcType=JdbcType.DECIMAL),
        @Result(column="EMAIL", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="ENABLESTATE", property="enablestate", jdbcType=JdbcType.DECIMAL),
        @Result(column="FIRSTNAME", property="firstname", jdbcType=JdbcType.VARCHAR),
        @Result(column="HOMEPHONE", property="homephone", jdbcType=JdbcType.VARCHAR),
        @Result(column="ID", property="id", jdbcType=JdbcType.VARCHAR),
        @Result(column="IDTYPE", property="idtype", jdbcType=JdbcType.VARCHAR),
        @Result(column="JOINWORKDATE", property="joinworkdate", jdbcType=JdbcType.CHAR),
        @Result(column="LASTNAME", property="lastname", jdbcType=JdbcType.VARCHAR),
        @Result(column="MNECODE", property="mnecode", jdbcType=JdbcType.VARCHAR),
        @Result(column="MOBILE", property="mobile", jdbcType=JdbcType.VARCHAR),
        @Result(column="MODIFIEDTIME", property="modifiedtime", jdbcType=JdbcType.CHAR),
        @Result(column="MODIFIER", property="modifier", jdbcType=JdbcType.VARCHAR),
        @Result(column="NAME", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="NAME2", property="name2", jdbcType=JdbcType.VARCHAR),
        @Result(column="NAME3", property="name3", jdbcType=JdbcType.VARCHAR),
        @Result(column="NAME4", property="name4", jdbcType=JdbcType.VARCHAR),
        @Result(column="NAME5", property="name5", jdbcType=JdbcType.VARCHAR),
        @Result(column="NAME6", property="name6", jdbcType=JdbcType.VARCHAR),
        @Result(column="NICKNAME", property="nickname", jdbcType=JdbcType.VARCHAR),
        @Result(column="OFFICEPHONE", property="officephone", jdbcType=JdbcType.VARCHAR),
        @Result(column="PK_GROUP", property="pkGroup", jdbcType=JdbcType.VARCHAR),
        @Result(column="PK_ORG", property="pkOrg", jdbcType=JdbcType.VARCHAR),
        @Result(column="SEX", property="sex", jdbcType=JdbcType.DECIMAL),
        @Result(column="TS", property="ts", jdbcType=JdbcType.CHAR),
        @Result(column="USEDNAME", property="usedname", jdbcType=JdbcType.VARCHAR),
        @Result(column="ISSHOPASSIST", property="isshopassist", jdbcType=JdbcType.CHAR),
        @Result(column="BLOODTYPE", property="bloodtype", jdbcType=JdbcType.VARCHAR),
        @Result(column="CENSUSADDR", property="censusaddr", jdbcType=JdbcType.VARCHAR),
        @Result(column="CHARACTERRPR", property="characterrpr", jdbcType=JdbcType.VARCHAR),
        @Result(column="COUNTRY", property="country", jdbcType=JdbcType.VARCHAR),
        @Result(column="DIE_DATE", property="dieDate", jdbcType=JdbcType.CHAR),
        @Result(column="DIE_REMARK", property="dieRemark", jdbcType=JdbcType.VARCHAR),
        @Result(column="EDU", property="edu", jdbcType=JdbcType.VARCHAR),
        @Result(column="FAX", property="fax", jdbcType=JdbcType.VARCHAR),
        @Result(column="FILEADDRESS", property="fileaddress", jdbcType=JdbcType.VARCHAR),
        @Result(column="HEALTH", property="health", jdbcType=JdbcType.VARCHAR),
        @Result(column="ISCADRE", property="iscadre", jdbcType=JdbcType.CHAR),
        @Result(column="ISHISKEYPSN", property="ishiskeypsn", jdbcType=JdbcType.CHAR),
        @Result(column="ISHISLEADER", property="ishisleader", jdbcType=JdbcType.CHAR),
        @Result(column="JOINPOLITYDATE", property="joinpolitydate", jdbcType=JdbcType.CHAR),
        @Result(column="MARITAL", property="marital", jdbcType=JdbcType.VARCHAR),
        @Result(column="MARRIAGEDATE", property="marriagedate", jdbcType=JdbcType.CHAR),
        @Result(column="NATIONALITY", property="nationality", jdbcType=JdbcType.VARCHAR),
        @Result(column="NATIVEPLACE", property="nativeplace", jdbcType=JdbcType.VARCHAR),
        @Result(column="PENELAUTH", property="penelauth", jdbcType=JdbcType.VARCHAR),
        @Result(column="PERMANRESIDE", property="permanreside", jdbcType=JdbcType.VARCHAR),
        @Result(column="PK_DEGREE", property="pkDegree", jdbcType=JdbcType.VARCHAR),
        @Result(column="PK_HRORG", property="pkHrorg", jdbcType=JdbcType.VARCHAR),
        @Result(column="POLITY", property="polity", jdbcType=JdbcType.VARCHAR),
        @Result(column="POSTALCODE", property="postalcode", jdbcType=JdbcType.VARCHAR),
        @Result(column="PROF", property="prof", jdbcType=JdbcType.CHAR),
        @Result(column="RETIREDATE", property="retiredate", jdbcType=JdbcType.CHAR),
        @Result(column="SECRET_EMAIL", property="secretEmail", jdbcType=JdbcType.VARCHAR),
        @Result(column="SHORTNAME", property="shortname", jdbcType=JdbcType.VARCHAR),
        @Result(column="TITLETECHPOST", property="titletechpost", jdbcType=JdbcType.VARCHAR),
        @Result(column="AGE", property="age", jdbcType=JdbcType.VARCHAR),
        @Result(column="WORKAGE", property="workage", jdbcType=JdbcType.VARCHAR),
        @Result(column="PHOTO", property="photo", jdbcType=JdbcType.BLOB),
        @Result(column="PREVIEWPHOTO", property="previewphoto", jdbcType=JdbcType.BLOB)
    })
    List<BdPsndocWithBLOBs> selectByExampleWithBLOBs(BdPsndocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BD_PSNDOC
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    @SelectProvider(type=BdPsndocSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="PK_PSNDOC", property="pkPsndoc", jdbcType=JdbcType.CHAR, id=true),
        @Result(column="ADDR", property="addr", jdbcType=JdbcType.VARCHAR),
        @Result(column="BIRTHDATE", property="birthdate", jdbcType=JdbcType.CHAR),
        @Result(column="CODE", property="code", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATIONTIME", property="creationtime", jdbcType=JdbcType.CHAR),
        @Result(column="CREATOR", property="creator", jdbcType=JdbcType.VARCHAR),
        @Result(column="DATAORIGINFLAG", property="dataoriginflag", jdbcType=JdbcType.DECIMAL),
        @Result(column="DEF1", property="def1", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF10", property="def10", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF11", property="def11", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF12", property="def12", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF13", property="def13", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF14", property="def14", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF15", property="def15", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF16", property="def16", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF17", property="def17", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF18", property="def18", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF19", property="def19", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF2", property="def2", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF20", property="def20", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF3", property="def3", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF4", property="def4", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF5", property="def5", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF6", property="def6", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF7", property="def7", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF8", property="def8", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF9", property="def9", jdbcType=JdbcType.VARCHAR),
        @Result(column="DR", property="dr", jdbcType=JdbcType.DECIMAL),
        @Result(column="EMAIL", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="ENABLESTATE", property="enablestate", jdbcType=JdbcType.DECIMAL),
        @Result(column="FIRSTNAME", property="firstname", jdbcType=JdbcType.VARCHAR),
        @Result(column="HOMEPHONE", property="homephone", jdbcType=JdbcType.VARCHAR),
        @Result(column="ID", property="id", jdbcType=JdbcType.VARCHAR),
        @Result(column="IDTYPE", property="idtype", jdbcType=JdbcType.VARCHAR),
        @Result(column="JOINWORKDATE", property="joinworkdate", jdbcType=JdbcType.CHAR),
        @Result(column="LASTNAME", property="lastname", jdbcType=JdbcType.VARCHAR),
        @Result(column="MNECODE", property="mnecode", jdbcType=JdbcType.VARCHAR),
        @Result(column="MOBILE", property="mobile", jdbcType=JdbcType.VARCHAR),
        @Result(column="MODIFIEDTIME", property="modifiedtime", jdbcType=JdbcType.CHAR),
        @Result(column="MODIFIER", property="modifier", jdbcType=JdbcType.VARCHAR),
        @Result(column="NAME", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="NAME2", property="name2", jdbcType=JdbcType.VARCHAR),
        @Result(column="NAME3", property="name3", jdbcType=JdbcType.VARCHAR),
        @Result(column="NAME4", property="name4", jdbcType=JdbcType.VARCHAR),
        @Result(column="NAME5", property="name5", jdbcType=JdbcType.VARCHAR),
        @Result(column="NAME6", property="name6", jdbcType=JdbcType.VARCHAR),
        @Result(column="NICKNAME", property="nickname", jdbcType=JdbcType.VARCHAR),
        @Result(column="OFFICEPHONE", property="officephone", jdbcType=JdbcType.VARCHAR),
        @Result(column="PK_GROUP", property="pkGroup", jdbcType=JdbcType.VARCHAR),
        @Result(column="PK_ORG", property="pkOrg", jdbcType=JdbcType.VARCHAR),
        @Result(column="SEX", property="sex", jdbcType=JdbcType.DECIMAL),
        @Result(column="TS", property="ts", jdbcType=JdbcType.CHAR),
        @Result(column="USEDNAME", property="usedname", jdbcType=JdbcType.VARCHAR),
        @Result(column="ISSHOPASSIST", property="isshopassist", jdbcType=JdbcType.CHAR),
        @Result(column="BLOODTYPE", property="bloodtype", jdbcType=JdbcType.VARCHAR),
        @Result(column="CENSUSADDR", property="censusaddr", jdbcType=JdbcType.VARCHAR),
        @Result(column="CHARACTERRPR", property="characterrpr", jdbcType=JdbcType.VARCHAR),
        @Result(column="COUNTRY", property="country", jdbcType=JdbcType.VARCHAR),
        @Result(column="DIE_DATE", property="dieDate", jdbcType=JdbcType.CHAR),
        @Result(column="DIE_REMARK", property="dieRemark", jdbcType=JdbcType.VARCHAR),
        @Result(column="EDU", property="edu", jdbcType=JdbcType.VARCHAR),
        @Result(column="FAX", property="fax", jdbcType=JdbcType.VARCHAR),
        @Result(column="FILEADDRESS", property="fileaddress", jdbcType=JdbcType.VARCHAR),
        @Result(column="HEALTH", property="health", jdbcType=JdbcType.VARCHAR),
        @Result(column="ISCADRE", property="iscadre", jdbcType=JdbcType.CHAR),
        @Result(column="ISHISKEYPSN", property="ishiskeypsn", jdbcType=JdbcType.CHAR),
        @Result(column="ISHISLEADER", property="ishisleader", jdbcType=JdbcType.CHAR),
        @Result(column="JOINPOLITYDATE", property="joinpolitydate", jdbcType=JdbcType.CHAR),
        @Result(column="MARITAL", property="marital", jdbcType=JdbcType.VARCHAR),
        @Result(column="MARRIAGEDATE", property="marriagedate", jdbcType=JdbcType.CHAR),
        @Result(column="NATIONALITY", property="nationality", jdbcType=JdbcType.VARCHAR),
        @Result(column="NATIVEPLACE", property="nativeplace", jdbcType=JdbcType.VARCHAR),
        @Result(column="PENELAUTH", property="penelauth", jdbcType=JdbcType.VARCHAR),
        @Result(column="PERMANRESIDE", property="permanreside", jdbcType=JdbcType.VARCHAR),
        @Result(column="PK_DEGREE", property="pkDegree", jdbcType=JdbcType.VARCHAR),
        @Result(column="PK_HRORG", property="pkHrorg", jdbcType=JdbcType.VARCHAR),
        @Result(column="POLITY", property="polity", jdbcType=JdbcType.VARCHAR),
        @Result(column="POSTALCODE", property="postalcode", jdbcType=JdbcType.VARCHAR),
        @Result(column="PROF", property="prof", jdbcType=JdbcType.CHAR),
        @Result(column="RETIREDATE", property="retiredate", jdbcType=JdbcType.CHAR),
        @Result(column="SECRET_EMAIL", property="secretEmail", jdbcType=JdbcType.VARCHAR),
        @Result(column="SHORTNAME", property="shortname", jdbcType=JdbcType.VARCHAR),
        @Result(column="TITLETECHPOST", property="titletechpost", jdbcType=JdbcType.VARCHAR),
        @Result(column="AGE", property="age", jdbcType=JdbcType.VARCHAR),
        @Result(column="WORKAGE", property="workage", jdbcType=JdbcType.VARCHAR)
    })
    List<BdPsndoc> selectByExample(BdPsndocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BD_PSNDOC
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    @Select({
        "select",
        "PK_PSNDOC, ADDR, BIRTHDATE, CODE, CREATIONTIME, CREATOR, DATAORIGINFLAG, DEF1, ",
        "DEF10, DEF11, DEF12, DEF13, DEF14, DEF15, DEF16, DEF17, DEF18, DEF19, DEF2, ",
        "DEF20, DEF3, DEF4, DEF5, DEF6, DEF7, DEF8, DEF9, DR, EMAIL, ENABLESTATE, FIRSTNAME, ",
        "HOMEPHONE, ID, IDTYPE, JOINWORKDATE, LASTNAME, MNECODE, MOBILE, MODIFIEDTIME, ",
        "MODIFIER, NAME, NAME2, NAME3, NAME4, NAME5, NAME6, NICKNAME, OFFICEPHONE, PK_GROUP, ",
        "PK_ORG, SEX, TS, USEDNAME, ISSHOPASSIST, BLOODTYPE, CENSUSADDR, CHARACTERRPR, ",
        "COUNTRY, DIE_DATE, DIE_REMARK, EDU, FAX, FILEADDRESS, HEALTH, ISCADRE, ISHISKEYPSN, ",
        "ISHISLEADER, JOINPOLITYDATE, MARITAL, MARRIAGEDATE, NATIONALITY, NATIVEPLACE, ",
        "PENELAUTH, PERMANRESIDE, PK_DEGREE, PK_HRORG, POLITY, POSTALCODE, PROF, RETIREDATE, ",
        "SECRET_EMAIL, SHORTNAME, TITLETECHPOST, AGE, WORKAGE, PHOTO, PREVIEWPHOTO",
        "from BD_PSNDOC",
        "where PK_PSNDOC = #{pkPsndoc,jdbcType=CHAR}"
    })
    @Results({
        @Result(column="PK_PSNDOC", property="pkPsndoc", jdbcType=JdbcType.CHAR, id=true),
        @Result(column="ADDR", property="addr", jdbcType=JdbcType.VARCHAR),
        @Result(column="BIRTHDATE", property="birthdate", jdbcType=JdbcType.CHAR),
        @Result(column="CODE", property="code", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATIONTIME", property="creationtime", jdbcType=JdbcType.CHAR),
        @Result(column="CREATOR", property="creator", jdbcType=JdbcType.VARCHAR),
        @Result(column="DATAORIGINFLAG", property="dataoriginflag", jdbcType=JdbcType.DECIMAL),
        @Result(column="DEF1", property="def1", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF10", property="def10", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF11", property="def11", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF12", property="def12", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF13", property="def13", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF14", property="def14", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF15", property="def15", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF16", property="def16", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF17", property="def17", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF18", property="def18", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF19", property="def19", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF2", property="def2", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF20", property="def20", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF3", property="def3", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF4", property="def4", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF5", property="def5", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF6", property="def6", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF7", property="def7", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF8", property="def8", jdbcType=JdbcType.VARCHAR),
        @Result(column="DEF9", property="def9", jdbcType=JdbcType.VARCHAR),
        @Result(column="DR", property="dr", jdbcType=JdbcType.DECIMAL),
        @Result(column="EMAIL", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="ENABLESTATE", property="enablestate", jdbcType=JdbcType.DECIMAL),
        @Result(column="FIRSTNAME", property="firstname", jdbcType=JdbcType.VARCHAR),
        @Result(column="HOMEPHONE", property="homephone", jdbcType=JdbcType.VARCHAR),
        @Result(column="ID", property="id", jdbcType=JdbcType.VARCHAR),
        @Result(column="IDTYPE", property="idtype", jdbcType=JdbcType.VARCHAR),
        @Result(column="JOINWORKDATE", property="joinworkdate", jdbcType=JdbcType.CHAR),
        @Result(column="LASTNAME", property="lastname", jdbcType=JdbcType.VARCHAR),
        @Result(column="MNECODE", property="mnecode", jdbcType=JdbcType.VARCHAR),
        @Result(column="MOBILE", property="mobile", jdbcType=JdbcType.VARCHAR),
        @Result(column="MODIFIEDTIME", property="modifiedtime", jdbcType=JdbcType.CHAR),
        @Result(column="MODIFIER", property="modifier", jdbcType=JdbcType.VARCHAR),
        @Result(column="NAME", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="NAME2", property="name2", jdbcType=JdbcType.VARCHAR),
        @Result(column="NAME3", property="name3", jdbcType=JdbcType.VARCHAR),
        @Result(column="NAME4", property="name4", jdbcType=JdbcType.VARCHAR),
        @Result(column="NAME5", property="name5", jdbcType=JdbcType.VARCHAR),
        @Result(column="NAME6", property="name6", jdbcType=JdbcType.VARCHAR),
        @Result(column="NICKNAME", property="nickname", jdbcType=JdbcType.VARCHAR),
        @Result(column="OFFICEPHONE", property="officephone", jdbcType=JdbcType.VARCHAR),
        @Result(column="PK_GROUP", property="pkGroup", jdbcType=JdbcType.VARCHAR),
        @Result(column="PK_ORG", property="pkOrg", jdbcType=JdbcType.VARCHAR),
        @Result(column="SEX", property="sex", jdbcType=JdbcType.DECIMAL),
        @Result(column="TS", property="ts", jdbcType=JdbcType.CHAR),
        @Result(column="USEDNAME", property="usedname", jdbcType=JdbcType.VARCHAR),
        @Result(column="ISSHOPASSIST", property="isshopassist", jdbcType=JdbcType.CHAR),
        @Result(column="BLOODTYPE", property="bloodtype", jdbcType=JdbcType.VARCHAR),
        @Result(column="CENSUSADDR", property="censusaddr", jdbcType=JdbcType.VARCHAR),
        @Result(column="CHARACTERRPR", property="characterrpr", jdbcType=JdbcType.VARCHAR),
        @Result(column="COUNTRY", property="country", jdbcType=JdbcType.VARCHAR),
        @Result(column="DIE_DATE", property="dieDate", jdbcType=JdbcType.CHAR),
        @Result(column="DIE_REMARK", property="dieRemark", jdbcType=JdbcType.VARCHAR),
        @Result(column="EDU", property="edu", jdbcType=JdbcType.VARCHAR),
        @Result(column="FAX", property="fax", jdbcType=JdbcType.VARCHAR),
        @Result(column="FILEADDRESS", property="fileaddress", jdbcType=JdbcType.VARCHAR),
        @Result(column="HEALTH", property="health", jdbcType=JdbcType.VARCHAR),
        @Result(column="ISCADRE", property="iscadre", jdbcType=JdbcType.CHAR),
        @Result(column="ISHISKEYPSN", property="ishiskeypsn", jdbcType=JdbcType.CHAR),
        @Result(column="ISHISLEADER", property="ishisleader", jdbcType=JdbcType.CHAR),
        @Result(column="JOINPOLITYDATE", property="joinpolitydate", jdbcType=JdbcType.CHAR),
        @Result(column="MARITAL", property="marital", jdbcType=JdbcType.VARCHAR),
        @Result(column="MARRIAGEDATE", property="marriagedate", jdbcType=JdbcType.CHAR),
        @Result(column="NATIONALITY", property="nationality", jdbcType=JdbcType.VARCHAR),
        @Result(column="NATIVEPLACE", property="nativeplace", jdbcType=JdbcType.VARCHAR),
        @Result(column="PENELAUTH", property="penelauth", jdbcType=JdbcType.VARCHAR),
        @Result(column="PERMANRESIDE", property="permanreside", jdbcType=JdbcType.VARCHAR),
        @Result(column="PK_DEGREE", property="pkDegree", jdbcType=JdbcType.VARCHAR),
        @Result(column="PK_HRORG", property="pkHrorg", jdbcType=JdbcType.VARCHAR),
        @Result(column="POLITY", property="polity", jdbcType=JdbcType.VARCHAR),
        @Result(column="POSTALCODE", property="postalcode", jdbcType=JdbcType.VARCHAR),
        @Result(column="PROF", property="prof", jdbcType=JdbcType.CHAR),
        @Result(column="RETIREDATE", property="retiredate", jdbcType=JdbcType.CHAR),
        @Result(column="SECRET_EMAIL", property="secretEmail", jdbcType=JdbcType.VARCHAR),
        @Result(column="SHORTNAME", property="shortname", jdbcType=JdbcType.VARCHAR),
        @Result(column="TITLETECHPOST", property="titletechpost", jdbcType=JdbcType.VARCHAR),
        @Result(column="AGE", property="age", jdbcType=JdbcType.VARCHAR),
        @Result(column="WORKAGE", property="workage", jdbcType=JdbcType.VARCHAR),
        @Result(column="PHOTO", property="photo", jdbcType=JdbcType.BLOB),
        @Result(column="PREVIEWPHOTO", property="previewphoto", jdbcType=JdbcType.BLOB)
    })
    BdPsndocWithBLOBs selectByPrimaryKey(String pkPsndoc);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BD_PSNDOC
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    @UpdateProvider(type=BdPsndocSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") BdPsndocWithBLOBs record, @Param("example") BdPsndocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BD_PSNDOC
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    @UpdateProvider(type=BdPsndocSqlProvider.class, method="updateByExampleWithBLOBs")
    int updateByExampleWithBLOBs(@Param("record") BdPsndocWithBLOBs record, @Param("example") BdPsndocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BD_PSNDOC
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    @UpdateProvider(type=BdPsndocSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") BdPsndoc record, @Param("example") BdPsndocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BD_PSNDOC
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    @UpdateProvider(type=BdPsndocSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(BdPsndocWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BD_PSNDOC
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    @Update({
        "update BD_PSNDOC",
        "set ADDR = #{addr,jdbcType=VARCHAR},",
          "BIRTHDATE = #{birthdate,jdbcType=CHAR},",
          "CODE = #{code,jdbcType=VARCHAR},",
          "CREATIONTIME = #{creationtime,jdbcType=CHAR},",
          "CREATOR = #{creator,jdbcType=VARCHAR},",
          "DATAORIGINFLAG = #{dataoriginflag,jdbcType=DECIMAL},",
          "DEF1 = #{def1,jdbcType=VARCHAR},",
          "DEF10 = #{def10,jdbcType=VARCHAR},",
          "DEF11 = #{def11,jdbcType=VARCHAR},",
          "DEF12 = #{def12,jdbcType=VARCHAR},",
          "DEF13 = #{def13,jdbcType=VARCHAR},",
          "DEF14 = #{def14,jdbcType=VARCHAR},",
          "DEF15 = #{def15,jdbcType=VARCHAR},",
          "DEF16 = #{def16,jdbcType=VARCHAR},",
          "DEF17 = #{def17,jdbcType=VARCHAR},",
          "DEF18 = #{def18,jdbcType=VARCHAR},",
          "DEF19 = #{def19,jdbcType=VARCHAR},",
          "DEF2 = #{def2,jdbcType=VARCHAR},",
          "DEF20 = #{def20,jdbcType=VARCHAR},",
          "DEF3 = #{def3,jdbcType=VARCHAR},",
          "DEF4 = #{def4,jdbcType=VARCHAR},",
          "DEF5 = #{def5,jdbcType=VARCHAR},",
          "DEF6 = #{def6,jdbcType=VARCHAR},",
          "DEF7 = #{def7,jdbcType=VARCHAR},",
          "DEF8 = #{def8,jdbcType=VARCHAR},",
          "DEF9 = #{def9,jdbcType=VARCHAR},",
          "DR = #{dr,jdbcType=DECIMAL},",
          "EMAIL = #{email,jdbcType=VARCHAR},",
          "ENABLESTATE = #{enablestate,jdbcType=DECIMAL},",
          "FIRSTNAME = #{firstname,jdbcType=VARCHAR},",
          "HOMEPHONE = #{homephone,jdbcType=VARCHAR},",
          "ID = #{id,jdbcType=VARCHAR},",
          "IDTYPE = #{idtype,jdbcType=VARCHAR},",
          "JOINWORKDATE = #{joinworkdate,jdbcType=CHAR},",
          "LASTNAME = #{lastname,jdbcType=VARCHAR},",
          "MNECODE = #{mnecode,jdbcType=VARCHAR},",
          "MOBILE = #{mobile,jdbcType=VARCHAR},",
          "MODIFIEDTIME = #{modifiedtime,jdbcType=CHAR},",
          "MODIFIER = #{modifier,jdbcType=VARCHAR},",
          "NAME = #{name,jdbcType=VARCHAR},",
          "NAME2 = #{name2,jdbcType=VARCHAR},",
          "NAME3 = #{name3,jdbcType=VARCHAR},",
          "NAME4 = #{name4,jdbcType=VARCHAR},",
          "NAME5 = #{name5,jdbcType=VARCHAR},",
          "NAME6 = #{name6,jdbcType=VARCHAR},",
          "NICKNAME = #{nickname,jdbcType=VARCHAR},",
          "OFFICEPHONE = #{officephone,jdbcType=VARCHAR},",
          "PK_GROUP = #{pkGroup,jdbcType=VARCHAR},",
          "PK_ORG = #{pkOrg,jdbcType=VARCHAR},",
          "SEX = #{sex,jdbcType=DECIMAL},",
          "TS = #{ts,jdbcType=CHAR},",
          "USEDNAME = #{usedname,jdbcType=VARCHAR},",
          "ISSHOPASSIST = #{isshopassist,jdbcType=CHAR},",
          "BLOODTYPE = #{bloodtype,jdbcType=VARCHAR},",
          "CENSUSADDR = #{censusaddr,jdbcType=VARCHAR},",
          "CHARACTERRPR = #{characterrpr,jdbcType=VARCHAR},",
          "COUNTRY = #{country,jdbcType=VARCHAR},",
          "DIE_DATE = #{dieDate,jdbcType=CHAR},",
          "DIE_REMARK = #{dieRemark,jdbcType=VARCHAR},",
          "EDU = #{edu,jdbcType=VARCHAR},",
          "FAX = #{fax,jdbcType=VARCHAR},",
          "FILEADDRESS = #{fileaddress,jdbcType=VARCHAR},",
          "HEALTH = #{health,jdbcType=VARCHAR},",
          "ISCADRE = #{iscadre,jdbcType=CHAR},",
          "ISHISKEYPSN = #{ishiskeypsn,jdbcType=CHAR},",
          "ISHISLEADER = #{ishisleader,jdbcType=CHAR},",
          "JOINPOLITYDATE = #{joinpolitydate,jdbcType=CHAR},",
          "MARITAL = #{marital,jdbcType=VARCHAR},",
          "MARRIAGEDATE = #{marriagedate,jdbcType=CHAR},",
          "NATIONALITY = #{nationality,jdbcType=VARCHAR},",
          "NATIVEPLACE = #{nativeplace,jdbcType=VARCHAR},",
          "PENELAUTH = #{penelauth,jdbcType=VARCHAR},",
          "PERMANRESIDE = #{permanreside,jdbcType=VARCHAR},",
          "PK_DEGREE = #{pkDegree,jdbcType=VARCHAR},",
          "PK_HRORG = #{pkHrorg,jdbcType=VARCHAR},",
          "POLITY = #{polity,jdbcType=VARCHAR},",
          "POSTALCODE = #{postalcode,jdbcType=VARCHAR},",
          "PROF = #{prof,jdbcType=CHAR},",
          "RETIREDATE = #{retiredate,jdbcType=CHAR},",
          "SECRET_EMAIL = #{secretEmail,jdbcType=VARCHAR},",
          "SHORTNAME = #{shortname,jdbcType=VARCHAR},",
          "TITLETECHPOST = #{titletechpost,jdbcType=VARCHAR},",
          "AGE = #{age,jdbcType=VARCHAR},",
          "WORKAGE = #{workage,jdbcType=VARCHAR},",
          "PHOTO = #{photo,jdbcType=BLOB},",
          "PREVIEWPHOTO = #{previewphoto,jdbcType=BLOB}",
        "where PK_PSNDOC = #{pkPsndoc,jdbcType=CHAR}"
    })
    int updateByPrimaryKeyWithBLOBs(BdPsndocWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BD_PSNDOC
     *
     * @mbg.generated Wed Sep 11 11:04:30 CST 2019
     */
    @Update({
        "update BD_PSNDOC",
        "set ADDR = #{addr,jdbcType=VARCHAR},",
          "BIRTHDATE = #{birthdate,jdbcType=CHAR},",
          "CODE = #{code,jdbcType=VARCHAR},",
          "CREATIONTIME = #{creationtime,jdbcType=CHAR},",
          "CREATOR = #{creator,jdbcType=VARCHAR},",
          "DATAORIGINFLAG = #{dataoriginflag,jdbcType=DECIMAL},",
          "DEF1 = #{def1,jdbcType=VARCHAR},",
          "DEF10 = #{def10,jdbcType=VARCHAR},",
          "DEF11 = #{def11,jdbcType=VARCHAR},",
          "DEF12 = #{def12,jdbcType=VARCHAR},",
          "DEF13 = #{def13,jdbcType=VARCHAR},",
          "DEF14 = #{def14,jdbcType=VARCHAR},",
          "DEF15 = #{def15,jdbcType=VARCHAR},",
          "DEF16 = #{def16,jdbcType=VARCHAR},",
          "DEF17 = #{def17,jdbcType=VARCHAR},",
          "DEF18 = #{def18,jdbcType=VARCHAR},",
          "DEF19 = #{def19,jdbcType=VARCHAR},",
          "DEF2 = #{def2,jdbcType=VARCHAR},",
          "DEF20 = #{def20,jdbcType=VARCHAR},",
          "DEF3 = #{def3,jdbcType=VARCHAR},",
          "DEF4 = #{def4,jdbcType=VARCHAR},",
          "DEF5 = #{def5,jdbcType=VARCHAR},",
          "DEF6 = #{def6,jdbcType=VARCHAR},",
          "DEF7 = #{def7,jdbcType=VARCHAR},",
          "DEF8 = #{def8,jdbcType=VARCHAR},",
          "DEF9 = #{def9,jdbcType=VARCHAR},",
          "DR = #{dr,jdbcType=DECIMAL},",
          "EMAIL = #{email,jdbcType=VARCHAR},",
          "ENABLESTATE = #{enablestate,jdbcType=DECIMAL},",
          "FIRSTNAME = #{firstname,jdbcType=VARCHAR},",
          "HOMEPHONE = #{homephone,jdbcType=VARCHAR},",
          "ID = #{id,jdbcType=VARCHAR},",
          "IDTYPE = #{idtype,jdbcType=VARCHAR},",
          "JOINWORKDATE = #{joinworkdate,jdbcType=CHAR},",
          "LASTNAME = #{lastname,jdbcType=VARCHAR},",
          "MNECODE = #{mnecode,jdbcType=VARCHAR},",
          "MOBILE = #{mobile,jdbcType=VARCHAR},",
          "MODIFIEDTIME = #{modifiedtime,jdbcType=CHAR},",
          "MODIFIER = #{modifier,jdbcType=VARCHAR},",
          "NAME = #{name,jdbcType=VARCHAR},",
          "NAME2 = #{name2,jdbcType=VARCHAR},",
          "NAME3 = #{name3,jdbcType=VARCHAR},",
          "NAME4 = #{name4,jdbcType=VARCHAR},",
          "NAME5 = #{name5,jdbcType=VARCHAR},",
          "NAME6 = #{name6,jdbcType=VARCHAR},",
          "NICKNAME = #{nickname,jdbcType=VARCHAR},",
          "OFFICEPHONE = #{officephone,jdbcType=VARCHAR},",
          "PK_GROUP = #{pkGroup,jdbcType=VARCHAR},",
          "PK_ORG = #{pkOrg,jdbcType=VARCHAR},",
          "SEX = #{sex,jdbcType=DECIMAL},",
          "TS = #{ts,jdbcType=CHAR},",
          "USEDNAME = #{usedname,jdbcType=VARCHAR},",
          "ISSHOPASSIST = #{isshopassist,jdbcType=CHAR},",
          "BLOODTYPE = #{bloodtype,jdbcType=VARCHAR},",
          "CENSUSADDR = #{censusaddr,jdbcType=VARCHAR},",
          "CHARACTERRPR = #{characterrpr,jdbcType=VARCHAR},",
          "COUNTRY = #{country,jdbcType=VARCHAR},",
          "DIE_DATE = #{dieDate,jdbcType=CHAR},",
          "DIE_REMARK = #{dieRemark,jdbcType=VARCHAR},",
          "EDU = #{edu,jdbcType=VARCHAR},",
          "FAX = #{fax,jdbcType=VARCHAR},",
          "FILEADDRESS = #{fileaddress,jdbcType=VARCHAR},",
          "HEALTH = #{health,jdbcType=VARCHAR},",
          "ISCADRE = #{iscadre,jdbcType=CHAR},",
          "ISHISKEYPSN = #{ishiskeypsn,jdbcType=CHAR},",
          "ISHISLEADER = #{ishisleader,jdbcType=CHAR},",
          "JOINPOLITYDATE = #{joinpolitydate,jdbcType=CHAR},",
          "MARITAL = #{marital,jdbcType=VARCHAR},",
          "MARRIAGEDATE = #{marriagedate,jdbcType=CHAR},",
          "NATIONALITY = #{nationality,jdbcType=VARCHAR},",
          "NATIVEPLACE = #{nativeplace,jdbcType=VARCHAR},",
          "PENELAUTH = #{penelauth,jdbcType=VARCHAR},",
          "PERMANRESIDE = #{permanreside,jdbcType=VARCHAR},",
          "PK_DEGREE = #{pkDegree,jdbcType=VARCHAR},",
          "PK_HRORG = #{pkHrorg,jdbcType=VARCHAR},",
          "POLITY = #{polity,jdbcType=VARCHAR},",
          "POSTALCODE = #{postalcode,jdbcType=VARCHAR},",
          "PROF = #{prof,jdbcType=CHAR},",
          "RETIREDATE = #{retiredate,jdbcType=CHAR},",
          "SECRET_EMAIL = #{secretEmail,jdbcType=VARCHAR},",
          "SHORTNAME = #{shortname,jdbcType=VARCHAR},",
          "TITLETECHPOST = #{titletechpost,jdbcType=VARCHAR},",
          "AGE = #{age,jdbcType=VARCHAR},",
          "WORKAGE = #{workage,jdbcType=VARCHAR}",
        "where PK_PSNDOC = #{pkPsndoc,jdbcType=CHAR}"
    })
    int updateByPrimaryKey(BdPsndoc record);
}