server:
  port: 8002
mybatis:
  mapper-locations: classpath:resources/mapper/*.xml
#  type-aliases-package: com.datatomq.demo.data
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.10.2.28:1521:orcl
    username: NC65_gold_0603
    password: sys
  redis:
    database: 0
    host: localhost
    port: 6379
